In [24]:
import pandas as pd
import os
import numpy as np
import pyodbc as odbc
from datetime import date,timedelta
import xlsxwriter
os.chdir(r'G:\FinanceReports\2024\Wk52')

In [58]:
# Names the needed driver, server name, and database
driver_name='SQL Server'
server_name='10.0.1.218'
database='ritascoolnet_live'
#Creates the connection string
connection_string=f"""
DRIVER={{{driver_name}}};
SERVER={server_name};
DATABASE={database};
Trust_Connection=yes"""
#Creates the Connection to SQL Server
connection=odbc.connect(connection_string)
print(connection)
data=pd.read_sql_query('''SELECT *
  FROM [ritas_bi].[dbo].[tmp_raw_plda]
  WHERE YEAR(EndDate)=2024
  ORDER BY Week DESC''',connection)
data1=pd.read_sql_query('''SELECT *
  FROM [ritas_bi].[dbo].[tmp_raw_plda]
  WHERE YEAR(StartDate)=2023
  ORDER BY Week DESC''',connection)
data4=pd.read_sql_query('''SELECT *
  FROM [ritas_bi].[dbo].[tmp_raw_plda]
  WHERE YEAR(StartDate)=2022
  ORDER BY Week DESC''',connection)
data2=pd.read_sql_query('''SELECT *
  FROM [ritas_bi].[dbo].[tmp_raw_pldb]
  WHERE YEAR(StartDate)=2021''',connection)
data3=pd.read_sql_query('''Select intstoreid as intStoreID,RitasID as ShopID, FC,CoolNetGroup,LegacyStoreType,State,MSAName,DMA,StoreName as ShopName,StoreStatus,[Special Venue] as SV,SeasonClose,[Parent Shop #] as ParentID from ritascoolnet_live.dbo.vShopDetail''',connection)

<pyodbc.Connection object at 0x0000016F43FBE030>

C:\Users\jharned\AppData\Local\Temp\ipykernel_26120\2185807557.py:29: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data3=pd.read_sql_query('''Select intstoreid as intStoreID,RitasID as ShopID, FC,CoolNetGroup,LegacyStoreType,State,MSAName,DMA,StoreName as ShopName,StoreStatus,[Special Venue] as SV,SeasonClose,[Parent Shop #] as ParentID from ritascoolnet_live.dbo.vShopDetail''',connection)

In [4]:
data[data.ProductTypeName=='Catering (Bulk Ice)'].ProductSizeName.unique()

array(['Gallon', 'Ice Super Fun Variety Pack', 'Catering Service Fee',
       '2.5 Gallon', 'Hand-Scooped Gallon', 'Container', '2 1/2 Gallon',
       'Gott Style Container', 'School Package',
       'All-Natural Small Catering Container Upcharge',
       'Small Catering Container', 'All-Natural 2 1/2 Gallon Upcharge',
       'All-Natural Fun Pack Upcharge'], dtype=object)

In [5]:
data[data.ProductTypeName=='Full Service Catering (Open $)'].ProductSizeName.unique()

array(['Full Service Catering', 'Catering Delivery Fee'], dtype=object)

In [6]:
data[(data.ProductTypeName=='Discount')].ProductSizeName.unique()

array(['Discount'], dtype=object)

In [7]:
data3.sort_values(by='ShopID').drop_duplicates(subset='ParentID',keep='first')

,intstoreid,ShopID,FC,CoolNetGroup,LegacyStoreType,State,MSAName,DMA,ShopName,StoreStatus,SV,SeasonClose,ParentID
0,20,0.0,None,Rita's Water ice Corporate,None,OH,None,None,Beachwood,None,No,NaT,0.0
2740,3817,1.0,Lindsey Goff,PA Thompson,Walk-up,PA,Philadelphia-Camden-Wilmington,Philadelphia,1227 Bristol Pk-Andalusia PA,Open,No,2024-10-06 00:00:00,1.0
458,779,2.0,Lindsey Goff,PA Brown Alan,Walk-up,PA,Philadelphia-Camden-Wilmington,Philadelphia,3244 Red Lion Rd-Phila PA,Open,No,2024-10-28 00:00:00,2.0
459,780,3.0,Lindsey Goff,PA Spangler,Walk-up,PA,Philadelphia-Camden-Wilmington,Philadelphia,Rising Sun,Transferred,No,2013-09-30 23:59:59,3.0
460,781,4.0,Lindsey Goff,PA Castle,Walk-up,PA,Philadelphia-Camden-Wilmington,Philadelphia,Pine Valley,Transferred,No,2015-10-11 23:59:59,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4456,5572,100249.0,Pete Skenteris,VA Wilson-Wilson,Walk-in / Walk-up,VA,None,None,Harrisonburg & Staunton VA Loc. 2,Sold!!!,No,NaT,100249.0
4460,5576,100251.0,Joe Toocheck,OH-KY Kattan,Walk-in / Walk-up,OH,None,None,Northern KY/OH Airport Area Loc. 2,Sold!!!,No,NaT,100251.0
888,1733,100255.0,Joe Toocheck,"KY Moore, Christa & Robert",Walk-in / Walk-up,KY,None,None,Florence & Covington KY Loc. 2,Sold!!!,No,NaT,100255.0
4383,5499,1000196.0,John Martin (FC),TX Raccuglia,Walk-in / Walk-up,TX,None,None,Williamson & Travis Counties TX Loc. 2,Sold!!!,None,NaT,1000196.0
10,35,NaN,None,Ritas Corporate,None,OH,None,None,Eastlake,None,None,NaT,NaN

In [10]:
data['Year']=data.StartDate.dt.year
data1['Year']=data1.StartDate.dt.year
data2['Year']=data2.StartDate.dt.year
data4['Year']=data4.StartDate.dt.year
all_data=pd.concat([data,data1,data2,data4])

In [56]:
all_data.shape

(2830643, 26)

In [60]:
all_data=all_data.merge(data3[['intStoreID','ParentID']],on='intStoreID',how='left')

In [67]:
all_data[(all_data.ParentID==71)&(all_data.Year==2022)].SalesMny.sum()

610046.4990000001

In [7]:
data['Year']=data.StartDate.dt.year
data1['Year']=data1.StartDate.dt.year
all_data=pd.concat([data,data1])
all_data=all_data[all_data.Week<=data.Week.max()]
ad=all_data.pivot_table(index=['ShopID'],columns='Year',values='SalesMny',aggfunc='sum',fill_value=0).reset_index()
comps=ad[(ad[2023]>0)&(ad[2024]>0)]
comps['Comps']='Yes'
all_data=all_data.merge(comps[['ShopID','Comps']],on='ShopID',how='left')
all_data['Comps']=all_data.Comps.fillna('No')
all_data.Comps.value_counts()

C:\Users\jharned\AppData\Local\Temp\ipykernel_2792\630284802.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comps['Comps']='Yes'

Comps
Yes    1449269
No       37927
Name: count, dtype: int64

In [8]:
data4=data3.sort_values(by='ShopID').drop_duplicates(subset='ParentID',keep='first')
all_data=all_data.merge(data4[['ShopID','DMA','SV','MSAName']],how='left',on='ShopID').drop_duplicates(keep='first')
all_data.head()

,ShopID,intStoreID,ProductCode,ProdSizeCode,DiscountCode,Register,SalesQty,SalesMny,StartDate,EndDate,...,ProductSizeName,SpecialVenue,CoOpStatus,CoOpName,CoOpRate,Year,Comps,DMA,SV,MSAName
0,518,2127,106,1254,126,1,1,0.00,2024-12-23,2024-12-29,...,GrubHub,No,No,None,0.00,2024,Yes,New York,No,New York-Newark-Jersey City
1,501,462,117,23,126,1,2,13.98,2024-12-23,2024-12-29,...,Blendini,No,Yes,"Washington, D.C.",0.02,2024,Yes,Washington DC,No,Washington-Arlington-Alexandria
2,498,660,64,1146,126,1,1,6.89,2024-12-23,2024-12-29,...,Small Frozen Coffee,No,No,None,0.00,2024,Yes,New York,No,New York-Newark-Jersey City
3,501,462,15,91,126,1,2,1.50,2024-12-23,2024-12-29,...,Whipped Cream,No,Yes,"Washington, D.C.",0.02,2024,Yes,Washington DC,No,Washington-Arlington-Alexandria
4,559,4877,5,113,126,1,8,10.32,2024-12-23,2024-12-29,...,Waffle Cone/Bowl Upcharge,No,No,None,0.00,2024,Yes,Norfolk-Portsmouth-Newport News,No,Virginia Beach-Norfolk-Newport News

In [9]:
# all_data.shape

In [10]:
# data[data.Week.between(16,19)].SalesMny.sum()

In [11]:
# data[data.Region.isna()]

In [12]:
# os.chdir(r'G:\FinanceReports')

In [13]:
# shops=[144,170,230,338,1265,1377,1390,1466,11390]
# data3[data3.ShopID.isin(shops)]

In [14]:
# data_3=pd.read_excel('2018-SRSsales-productLevel-2.xlsx', sheet_name='2018')
# data_4=pd.read_excel('2019-SRSsales-productLevel-2.xlsx', sheet_name='2019')
# data_5=pd.read_excel('2017-SRSsales-productLevel-2.xlsx',sheet_name='2017')

In [15]:
# os.chdir(r'G:\FinanceReports\YTD Files')
# data_6=pd.read_excel('2020-SRSsales-productLevel-wk1-53.xlsx', sheet_name='2020')

In [16]:
# sales_23=data.SalesMny.sum()
# sales_22=data1.SalesMny.sum()
# # sales_21=data2.SalesMny.sum()
# # sales_20=data_6.SalesMny.sum()
# # sales_19=data_4.SalesMny.sum()
# # sales_18=data_3.SalesMny.sum()
# # sales_17=data_5.SalesMny.sum()
# qty_23=data.SalesQty.sum()
# qty_22=data1.SalesQty.sum()
# # qty_21=data2.SalesQty.sum()
# # qty_20=data_6.SalesQty.sum()
# # qty_19=data_4.SalesQty.sum()
# # qty_18=data_3.SalesQty.sum()
# # qty_17=data_5.SalesQty.sum()

In [17]:
# pmix_item23=data.pivot_table(index='ProductSizeName',values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
# pmix_item23['Sales%']=pmix_item23.SalesMny/sales_23
# pmix_item23['Qty%']=pmix_item23.SalesQty/qty_23
# pmix_item23

In [18]:
# pmix_item23=data.pivot_table(index='ProductTypeName',values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
# pmix_item23['Sales%']=pmix_item23.SalesMny/sales_23
# pmix_item23['Qty%']=pmix_item23.SalesQty/qty_23
# pmix_item23

In [19]:
# pmix_item22=data1.pivot_table(index='ProductSizeName',values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
# pmix_item22['Sales%']=pmix_item22.SalesMny/sales_22
# pmix_item22['Qty%']=pmix_item22.SalesQty/qty_22
# pmix_item22.to_excel('PMIX 2022.xlsx',index=False)

In [20]:
# pmix_item21=data2.pivot_table(index='ProductSizeName',values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
# pmix_item21['Sales%']=pmix_item21.SalesMny/sales_21
# pmix_item21['Qty%']=pmix_item21.SalesQty/qty_21
# pmix_item21

In [21]:
# pmix_item20=data_6.pivot_table(index='ProductSizeName',values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
# pmix_item20['Sales%']=pmix_item20.SalesMny/sales_20
# pmix_item20['Qty%']=pmix_item20.SalesQty/qty_20
# pmix_item20

In [22]:
# pmix_item19=data_4.pivot_table(index='ProductSizeName',values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
# pmix_item19['Sales%']=pmix_item19.SalesMny/sales_19
# pmix_item19['Qty%']=pmix_item19.SalesQty/qty_19
# pmix_item19

In [23]:
# pmix_item18=data_3.pivot_table(index='ProductSizeName',values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
# pmix_item18['Sales%']=pmix_item18.SalesMny/sales_18
# pmix_item18['Qty%']=pmix_item18.SalesQty/qty_18
# pmix_item18

In [24]:
# pmix_item17=data_5.pivot_table(index='ProductSizeName',values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
# pmix_item17['Sales%']=pmix_item17.SalesMny/sales_17
# pmix_item17['Qty%']=pmix_item17.SalesQty/qty_17
# pmix_item17.rename(columns={'SalesMny':'Sales_17','SalesQty':'Qty_17','Sales%':'Sales%_17','Qty%':'Qty%_17'})

In [25]:
# writer=pd.ExcelWriter('PMIX 2017-23.xlsx')
# pmix_item23.sort_values(by='Sales%',ascending=False).to_excel(writer,sheet_name='2023',index=False)
# pmix_item22.sort_values(by='Sales%',ascending=False).to_excel(writer,sheet_name='2022',index=False)
# pmix_item21.sort_values(by='Sales%',ascending=False).to_excel(writer,sheet_name='2021',index=False)
# pmix_item20.sort_values(by='Sales%',ascending=False).to_excel(writer,sheet_name='2020',index=False)
# pmix_item19.sort_values(by='Sales%',ascending=False).to_excel(writer,sheet_name='2019',index=False)
# pmix_item18.sort_values(by='Sales%',ascending=False).to_excel(writer,sheet_name='2018',index=False)
# pmix_item17.sort_values(by='Sales%',ascending=False).to_excel(writer,sheet_name='2017',index=False)
# writer.save()
# writer.close()

In [26]:
# # pmix_item17.rename(columns={'SalesMny':'Sales_17','SalesQty':'Qty_17','Sales%':'Sales%_17','Qty%':'Qty%_17'},inplace=True)
# # pmix_item18.rename(columns={'SalesMny':'Sales_18','SalesQty':'Qty_18','Sales%':'Sales%_18','Qty%':'Qty%_18'},inplace=True)
# # pmix_item19.rename(columns={'SalesMny':'Sales_19','SalesQty':'Qty_19','Sales%':'Sales%_19','Qty%':'Qty%_19'},inplace=True)
# # pmix_item20.rename(columns={'SalesMny':'Sales_20','SalesQty':'Qty_20','Sales%':'Sales%_20','Qty%':'Qty%_20'},inplace=True)
# # pmix_item21.rename(columns={'SalesMny':'Sales_21','SalesQty':'Qty_21','Sales%':'Sales%_21','Qty%':'Qty%_21'},inplace=True)
# # pmix_item22.rename(columns={'SalesMny':'Sales_22','SalesQty':'Qty_22','Sales%':'Sales%_22','Qty%':'Qty%_22'},inplace=True)
# pmix_item23.rename(columns={'SalesMny':'Sales_23','SalesQty':'Qty_23','Sales%':'Sales%_23','Qty%':'Qty%_23'},inplace=True)

In [27]:
# pmix_all_years=pmix_item23.merge(pmix_item22,how='outer',on='ProductSizeName').merge(pmix_item21,how='outer',on='ProductSizeName').merge(pmix_item20,how='outer',on='ProductSizeName').merge(pmix_item19,
#     how='outer',on='ProductSizeName').merge(pmix_item18,how='outer',on='ProductSizeName').merge(pmix_item17,how='outer',on='ProductSizeName').fillna(0)

In [28]:
# pmix_all_years.to_excel('PMIX Combined.xlsx',index=False)

In [29]:
# pmix_all_years

In [30]:
# pmix_22=data1[data1.Week<=45].pivot_table(index='ProductTypeName',values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
# pmix_22['Sales%']=pmix_22.SalesMny/sales_22
# pmix_22['Qty%']=pmix_22.SalesQty/qty_22
# pmix_22.to_excel('PMIX 2022.xlsx',index=False)

In [31]:
# pmix_23=data.pivot_table(index='ProductTypeName',values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
# pmix_23['Sales%']=pmix_23.SalesMny/sales_23
# pmix_23['Qty%']=pmix_23.SalesQty/qty_23

In [32]:
# pmix_21=data2.pivot_table(index='ProductTypeName',values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
# pmix_21['Sales%']=pmix_21.SalesMny/sales_21
# pmix_21['Qty%']=pmix_21.SalesQty/qty_21

In [33]:
# pmix_20=data_6.pivot_table(index='ProductTypeName',values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
# pmix_20['Sales%']=pmix_20.SalesMny/sales_20
# pmix_20['Qty%']=pmix_20.SalesQty/qty_20

In [34]:
# pmix_19=data_4.pivot_table(index='ProductTypeName',values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
# pmix_19['Sales%']=pmix_19.SalesMny/sales_19
# pmix_19['Qty%']=pmix_19.SalesQty/qty_19

In [35]:
# pmix_18=data_3.pivot_table(index='ProductTypeName',values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
# pmix_18['Sales%']=pmix_18.SalesMny/sales_18
# pmix_18['Qty%']=pmix_18.SalesQty/qty_18

In [36]:
# pmix_17=data_5.pivot_table(index='ProductTypeName',values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
# pmix_17['Sales%']=pmix_17.SalesMny/sales_17
# pmix_17['Qty%']=pmix_17.SalesQty/qty_17

In [37]:
# writer=pd.ExcelWriter('PMIX Category 2017-23.xlsx')
# pmix_23.sort_values(by='Sales%',ascending=False).to_excel(writer,sheet_name='2023',index=False)
# pmix_22.sort_values(by='Sales%',ascending=False).to_excel(writer,sheet_name='2022',index=False)
# pmix_21.sort_values(by='Sales%',ascending=False).to_excel(writer,sheet_name='2021',index=False)
# pmix_20.sort_values(by='Sales%',ascending=False).to_excel(writer,sheet_name='2020',index=False)
# pmix_19.sort_values(by='Sales%',ascending=False).to_excel(writer,sheet_name='2019',index=False)
# pmix_18.sort_values(by='Sales%',ascending=False).to_excel(writer,sheet_name='2018',index=False)
# pmix_17.sort_values(by='Sales%',ascending=False).to_excel(writer,sheet_name='2017',index=False)
# writer.save()
# writer.close()

In [38]:
# pmix_17.rename(columns={'SalesMny':'Sales_17','SalesQty':'Qty_17','Sales%':'Sales%_17','Qty%':'Qty%_17'},inplace=True)
# pmix_18.rename(columns={'SalesMny':'Sales_18','SalesQty':'Qty_18','Sales%':'Sales%_18','Qty%':'Qty%_18'},inplace=True)
# pmix_19.rename(columns={'SalesMny':'Sales_19','SalesQty':'Qty_19','Sales%':'Sales%_19','Qty%':'Qty%_19'},inplace=True)
# pmix_20.rename(columns={'SalesMny':'Sales_20','SalesQty':'Qty_20','Sales%':'Sales%_20','Qty%':'Qty%_20'},inplace=True)
# pmix_21.rename(columns={'SalesMny':'Sales_21','SalesQty':'Qty_21','Sales%':'Sales%_21','Qty%':'Qty%_21'},inplace=True)
# pmix_22.rename(columns={'SalesMny':'Sales_22','SalesQty':'Qty_22','Sales%':'Sales%_22','Qty%':'Qty%_22'},inplace=True)
# pmix_23.rename(columns={'SalesMny':'Sales_23','SalesQty':'Qty_23','Sales%':'Sales%_23','Qty%':'Qty%_23'},inplace=True)

In [39]:
# pmix_23.merge(pmix_22,how='outer',on='ProductTypeName').merge(pmix_21,how='outer',on='ProductTypeName').merge(pmix_20,how='outer',on='ProductTypeName').merge(pmix_19,
#     how='outer',on='ProductTypeName').merge(pmix_18,how='outer',on='ProductTypeName').merge(pmix_17,how='outer',on='ProductTypeName').fillna(0).to_excel('Combinded Category PMIX.xlsx',index=False)

In [40]:
# shops=[164,241,445,559,20,43,48,1446,124,189,1418,1517,1526,1212,1413,156,71,501,413,691,836]
# bri_shops=data[data.ShopID.isin(shops)].pivot_table(index='ProductSizeName',columns='ShopID',
#                                                  values='SalesMny',aggfunc=sum,fill_value=0).apply(
# lambda x:x/sum(x))

In [41]:
# madalyn=pd.merge(bri_shops,pmix_item23[['ProductSizeName','Sales%_23']],on='ProductSizeName',how='outer').fillna(0)
# madalyn.iloc[:,np.r_[0,-1,1:len(madalyn.columns)-1]].to_excel('Madalyn Pmix.xlsx',index=False)

In [42]:
# pd.merge(bri_shops,pmix_item23[['ProductTypeName','Sales%_23']],on='ProductTypeName',how='outer').fillna(0)#.to_excel(
#     #'Pmix Shops for Bri.xlsx',index=False)

# For Natalie

In [43]:
all_data.columns

Index(['ShopID', 'intStoreID', 'ProductCode', 'ProdSizeCode', 'DiscountCode',
       'Register', 'SalesQty', 'SalesMny', 'StartDate', 'EndDate', 'EditDate',
       'Week', 'DataSource', 'ShopName', 'State', 'Region', 'ShopStatus',
       'LegacyShopType', 'LegacyShopStatus', 'ProductTypeName',
       'ProductSizeName', 'SpecialVenue', 'CoOpStatus', 'CoOpName', 'CoOpRate',
       'Year', 'Comps', 'DMA', 'SV', 'MSAName'],
      dtype='object')

In [44]:
# data1=data1.merge(data3[['ShopID','DMA','MSAName','SeasonClose','SV']],how='left',on='ShopID').drop_duplicates(keep='first')
# data1.shape

In [45]:
data=data.merge(comps[['ShopID','Comps']],on='ShopID',how='left')
data['Comps']=data.Comps.fillna('No')
data.Comps.value_counts()

Comps
Yes    772955
No      23172
Name: count, dtype: int64

In [46]:
data.columns

Index(['ShopID', 'intStoreID', 'ProductCode', 'ProdSizeCode', 'DiscountCode',
       'Register', 'SalesQty', 'SalesMny', 'StartDate', 'EndDate', 'EditDate',
       'Week', 'DataSource', 'ShopName', 'State', 'Region', 'ShopStatus',
       'LegacyShopType', 'LegacyShopStatus', 'ProductTypeName',
       'ProductSizeName', 'SpecialVenue', 'CoOpStatus', 'CoOpName', 'CoOpRate',
       'Year', 'Comps'],
      dtype='object')

# 2024 PMIX

In [72]:
data=all_data[all_data.Year==2023]
def category(data, 
         dma=None, coop=None, msa=None, shopid=None, state=None, region=None,
         sv=None, comp=None, week_min=1, week_max=None):
    """
    Generate a pivot table summarizing sales and quantities for different filters.

    Parameters:
        data (pd.DataFrame): Dataset containing sales data.
        dma (list, optional): List of DMAs to filter by.
        coop (list, optional): List of CoOps to filter by.
        msa (str, optional): Substring to match in MSA names.
        shopid (list, optional): List of ShopIDs to filter by.
        state (list, optional): List of states to filter by.
        region (list, optional): List of regions to filter by.
        sv (str, optional): SV filter (default is '').
        comp (str, optional): Comp filter (default is '').
        week_min (int, optional): Minimum week number for filtering (default is 1).
        week_max (int, optional): Maximum week number for filtering (default is data's max week).

    Returns:
        pd.DataFrame: Pivot table summarizing sales and quantities by `ProductTypeName`, 
                      including percentages of sales and quantity.
    """
    # Set default week_max if not provided
    if week_max is None:
        week_max = data.Week.max()

    # Create a base filter
    base_filter = (data.Week.between(week_min, week_max))

    # Add additional filters based on provided arguments
    if shopid:
        base_filter &= data.ParentID.isin(shopid)
    if dma:
        base_filter &= data.DMA.isin(dma)
    if coop:
        base_filter &= data.CoOpName.isin(coop)
    if msa:
        base_filter &= data.MSAName.str.contains(msa, na=False)
    if state:
        base_filter &= data.State.isin(state)
    if region:
        base_filter &= data.Region.isin(region)
    if sv:
        base_filter &= (data.SpecialVenue==sv)
    if comp:
        base_filter &= (data.Comps==comp)

    # Filter the data
    filtered_data = data[base_filter]

    # Check for empty filtered data
    if filtered_data.empty:
        return pd.DataFrame({'Message': ['No data found for the given filters']})

    # Calculate total sales and quantities
    total_sales = filtered_data.SalesMny.sum()
    total_qty = filtered_data.SalesQty.sum()

    # Create the pivot table
    item24 = filtered_data.pivot_table(
        index='ProductTypeName',
        values=['SalesMny', 'SalesQty'],
        aggfunc='sum'
    ).reset_index()

    # Add percentage columns
    item24['Sales%'] = item24['SalesMny'] / total_sales
    item24['Qty%'] = item24['SalesQty'] / total_qty
    item24=item24.rename(columns={'SalesMny':'Sales','SalesQty':'Volume'})
    
    return item24

In [73]:
data=all_data[all_data.Year==2023]
def item(data, 
         dma=None, coop=None, msa=None, shopid=None, state=None, region=None,
         sv=None, comp=None, week_min=1, week_max=None):
    """
    Generate a pivot table summarizing sales and quantities for different filters.

    Parameters:
        data (pd.DataFrame): Dataset containing sales data.
        dma (list, optional): List of DMAs to filter by.
        coop (list, optional): List of CoOps to filter by.
        msa (str, optional): Substring to match in MSA names.
        shopid (list, optional): List of ShopIDs to filter by.
        state (list, optional): List of states to filter by.
        region (list, optional): List of regions to filter by.
        sv (str, optional): SV filter (default is '').
        comp (str, optional): Comp filter (default is '').
        week_min (int, optional): Minimum week number for filtering (default is 1).
        week_max (int, optional): Maximum week number for filtering (default is data's max week).

    Returns:
        pd.DataFrame: Pivot table summarizing sales and quantities by `ProductTypeName`, 
                      including percentages of sales and quantity.
    """
    # Set default week_max if not provided
    if week_max is None:
        week_max = data.Week.max()

    # Create a base filter
    base_filter = (data.Week.between(week_min, week_max))

    # Add additional filters based on provided arguments
    if shopid:
        base_filter &= data.ParentID.isin(shopid)
    if dma:
        base_filter &= data.DMA.isin(dma)
    if coop:
        base_filter &= data.CoOpName.isin(coop)
    if msa:
        base_filter &= data.MSAName.str.contains(msa, na=False)
    if state:
        base_filter &= data.State.isin(state)
    if region:
        base_filter &= data.Region.isin(region)
    if sv:
        base_filter &= (data.SpecialVenue==sv)
    if comp:
        base_filter &= (data.Comps==comp)

    # Filter the data
    filtered_data = data[base_filter]

    # Check for empty filtered data
    if filtered_data.empty:
        return pd.DataFrame({'Message': ['No data found for the given filters']})

    # Calculate total sales and quantities
    total_sales = filtered_data.SalesMny.sum()
    total_qty = filtered_data.SalesQty.sum()

    # Create the pivot table
    item23 = filtered_data.pivot_table(
        index='ProductSizeName',
        values=['SalesMny', 'SalesQty'],
        aggfunc='sum'
    ).reset_index()

    # Add percentage columns
    item23['Sales%'] = item23['SalesMny'] / total_sales
    item23['Qty%'] = item23['SalesQty'] / total_qty
    item23=item23.rename(columns={'SalesMny':'Sales','SalesQty':'Volume'})

    return item23

In [53]:
data[data.ShopID==71].SalesMny.sum()

503631.7866

In [38]:
item(data=data,shopid=[71],week_min=1)

                       ProductSizeName      Sales  Volume    Sales%      Qty%
0                           2.5 Gallon    119.980       2  0.000242  0.000024
1                       5-Layer Gelati   1837.270     283  0.003705  0.003450
2     6-pack Custard Cookie Sandwiches   3682.841     286  0.007426  0.003486
3                    8in Color Ice Guy      0.000       0  0.000000  0.000000
4                   Additional Topping   3946.140    3986  0.007957  0.048591
5                             Blendini   6737.220    1008  0.013584  0.012288
6                Catering Delivery Fee      0.000       0  0.000000  0.000000
7                             Concrete  13762.071    1913  0.027749  0.023320
8                             Discount  -2805.190       0 -0.005656  0.000000
9                             DoorDash  41175.090       0  0.083022  0.000000
10                 FDOS Custard Topper     54.830      39  0.000111  0.000475
11               Full Service Catering  34267.790      37  0.069095  0.000451
12                              Gallon   2604.130      87  0.005251  0.001061
13                             GrubHub      0.000       0  0.000000  0.000000
14                         Ice Flights   3735.740     626  0.007532  0.007631
15          Ice Super Fun Variety Pack    449.950       5  0.000907  0.000061
16  Individual Custard Cookie Sandwich   1522.110     468  0.003069  0.005705
17     Individual Jumbo Custard Cookie      4.490       1  0.000009  0.000012
18                            Kids Ice   8277.510    2249  0.016690  0.027416
19                    Kids SS Cup/Cone   3565.470     913  0.007189  0.011130
20             King Size Super Pretzel   1669.450     560  0.003366  0.006827
21                Large Brownie Sundae      0.000       0  0.000000  0.000000
22                        Large Gelati  77243.021   13041  0.155747  0.158975
23                Large Gelati Blender  10641.441    1838  0.021457  0.022406
24                           Large Ice  43608.231    8932  0.087928  0.108884
25                   Large Ice Blender   5369.653     944  0.010827  0.011508
26                     Large Milkshake  10252.710    1291  0.020673  0.015738
27                   Large SS Cup/Cone  22093.160    4234  0.044547  0.051614
28                     Large SS Sundae   6277.850     915  0.012658  0.011154
29       Other 3rd Party Deliv Non MFA      0.000       0  0.000000  0.000000
30                      Philly Pretzel      0.000       0  0.000000  0.000000
31                       Plush Ice Guy     84.000      11  0.000169  0.000134
32               Pre-packaged Toppings      0.000       0  0.000000  0.000000
33                           Quart Ice  15417.870    1937  0.031087  0.023613
34                 Ritas Bottled Water    405.550     229  0.000818  0.002792
35                    SS Custard Pints   1578.040     198  0.003182  0.002414
36                    SS Extra Custard   1080.500     875  0.002179  0.010667
37                Small Brownie Sundae      0.000       0  0.000000  0.000000
38                        Small Gelati  44256.451    8160  0.089235  0.099473
39                Small Gelati Blender   5311.160    1004  0.010709  0.012239
40                           Small Ice  42250.000    9650  0.085190  0.117637
41                   Small Ice Blender   2818.170     543  0.005682  0.006619
42                     Small Milkshake   7592.660    1094  0.015309  0.013336
43                   Small SS Cup/Cone  33402.500    7080  0.067350  0.086308
44                     Small SS Sundae   6615.560    1044  0.013339  0.012727
45                  Sprinkles Upcharge   4574.600    5140  0.009224  0.062658
46                   Take Home Custard      0.000       0  0.000000  0.000000
47                            UberEats  29076.250       0  0.058627  0.000000
48           Waffle Cone/Bowl Upcharge   1394.910    1409  0.002813  0.017176

In [74]:
    cat=category(data=data,shopid=[71],week_min=1).sort_values(by='Sales',ascending=False).set_index('ProductTypeName')
    it=item(data=data,shopid=[71],week_min=1).sort_values(by='Sales',ascending=False).set_index('ProductSizeName')

    writer=pd.ExcelWriter('2023 PMIX for Shop 71 Woodhaven.xlsx')
    cat.to_excel(writer,sheet_name='Category',startrow=5, startcol=0)
    it.to_excel(writer,sheet_name='Item',startrow=5, startcol=0)
    
    wb=writer.book
    dollar_format=wb.add_format({'num_format':'$#,##0.00'})
    perc_format=wb.add_format({'num_format':'0.0%'})
    vol_format=wb.add_format({'num_format':'#,##0'})
    header_format=wb.add_format({'bold':True,'italic':True,'align':'center','valign':'vcenter'})
    border_format=wb.add_format({'top':1,'bottom':1,'left':1,'right':1})
    odd_row_format = wb.add_format({'bg_color': '#FFFFFF'})  # White for odd rows
    even_row_format = wb.add_format({'bg_color': '#DCE6F1'})  # Light Blue for even rows
    col_header=wb.add_format({'bg_color':'#8DB4E2','bold':True,'align':'center','valign':'vcenter'})
    word_format=wb.add_format({'align':'center','valign':'vcenter','text_wrap':True})
    
    ws=writer.sheets['Category']
    ws1=writer.sheets['Item']
    
    #Creates the Header Text
    text1='Ritas Franchise Company,LLC'
    text2='2023 Product Mix Report by Category'
    text3='2023 Product Mix Report by Item'
    text4='Shop 71 Woodhaven - All Sales Rolled Up to Parent Shop'
    text5='Source Code: ritascoolnet_live-tmp_raw_pdla, vShopDetail'
    
    ws.write(0,2,text1,header_format)
    ws.write(1,2,text2,header_format)
    ws.write(2,2,text4,header_format)
    ws.write(3,2,text5,header_format)
    
    ws.set_column('A:A',25,word_format)
    ws.set_column('B:B',12,dollar_format)
    ws.set_column('C:C',12,vol_format)
    ws.set_column('D:E',12,perc_format)
    
    ws.conditional_format(xlsxwriter.utility.xl_range(5,0,len(cat)+5,len(cat.columns)),
                              {'type': 'no_errors', 'format': border_format})
    ws.conditional_format(6, 0, len(cat) + 5, len(cat.columns), {
                'type': 'formula',
                'criteria': 'ISEVEN(ROW()-5)',
                'format': even_row_format
            })
    ws.conditional_format(6, 0, len(cat) + 5, len(cat.columns), {
                'type': 'formula',
                'criteria': 'ISODD(ROW()-5)',
                'format': odd_row_format
            })
    
    ws.insert_image('A1','Logo.png')
    ws.hide_gridlines(2)
    ws.write_row('A6',cat.reset_index().columns,col_header)
    
    ws1.write(0,2,text1,header_format)
    ws1.write(1,2,text3,header_format)
    ws1.write(2,2,text4,header_format)
    ws1.write(3,2,text5,header_format)
    
    ws1.set_column('A:A',32,word_format)
    ws1.set_column('B:B',12,dollar_format)
    ws1.set_column('C:C',12,vol_format)
    ws1.set_column('D:E',12,perc_format)
    
    ws1.conditional_format(xlsxwriter.utility.xl_range(5,0,len(it)+5,len(it.columns)),
                              {'type': 'no_errors', 'format': border_format})
    ws1.conditional_format(6, 0, len(it) + 5, len(it.columns), {
                'type': 'formula',
                'criteria': 'ISEVEN(ROW()-5)',
                'format': even_row_format
            })
    ws1.conditional_format(6, 0, len(it) + 5, len(it.columns), {
                'type': 'formula',
                'criteria': 'ISODD(ROW()-5)',
                'format': odd_row_format
            })
    
    ws1.insert_image('A1','Logo.png')
    ws1.hide_gridlines(2)
    ws1.write_row('A6',it.reset_index().columns,col_header)
    writer.close()

In [ ]:
data.Comps

In [ ]:
data[(data.State=='FL')&(data.Week.between(9,39))&(data.SV=='No')&(data.Year==2024)].SalesMny.sum()

In [ ]:
# shops=data[data.ProductSizeName=='Individual Custard Cookie Sandwich'].ShopID.unique()
pmix(state=['FL'],week_min=9,week_max=39,sv='No',comp='Yes').sum(axis=0)

In [56]:
import xlsxwriter
with pd.ExcelWriter('2024 PMIX Week 1-49.xlsx',engine='xlsxwriter') as writer:
    philly=pmix(data,shopid=0,dma=['Philadelphia'],week_min=1,week_max=49,sv='No',comp='Yes')
    philly.to_excel(writer,sheet_name='Philly',startrow=5,startcol=0,index=False)
    balt=pmix(data,shopid=0,dma=['Baltimore'],week_min=1,week_max=49,sv='No',comp='Yes')
    balt.to_excel(writer,sheet_name='Baltimore',startrow=5,startcol=0,index=False)
    dc=pmix(data,shopid=0,dma=['Washington DC'],week_min=1,week_max=49,sv='No',comp='Yes')
    dc.to_excel(writer,sheet_name='DC',startrow=5,startcol=0,index=False)
    pitt=pmix(data,shopid=0,dma=['Pittsburgh'],week_min=1,week_max=49,sv='No',comp='Yes')
    pitt.to_excel(writer,sheet_name='Pittsburgh',startrow=5,startcol=0,index=False)
    hlly=pmix(data,shopid=0,dma=['Harrisburg-Lancaster-Lebanon-York'],week_min=1,week_max=49,sv='No',comp='Yes')
    hlly.to_excel(writer,sheet_name='HLLY',startrow=5,startcol=0,index=False)
    wbs=pmix(data,shopid=0,dma=['Wilkes Barre-Scranton'],week_min=1,week_max=49,sv='No',comp='Yes')
    wbs.to_excel(writer,sheet_name='WBS',startrow=5,startcol=0,index=False)
    
    mid=pmix(data,shopid=0,state=['CT','DC','DE','MA','MD','NJ','NY','PA','VA','WV'],week_min=1,week_max=49,sv='No',comp='Yes')
    mid.to_excel(writer,sheet_name='MID-NE',startrow=5,startcol=0,index=False)
    
    mw=pmix(data,shopid=0,state=['IL','IN','KY','OH','MI','MN','MO'],week_min=1,week_max=49,sv='No',comp='Yes')
    mw.to_excel(writer,sheet_name='Midwest',startrow=5,startcol=0,index=False)
    
    south=pmix(data,shopid=0,state=['SC',
           'GA','NC','TN','AL'],week_min=1,week_max=49,sv='No',comp='Yes')
    south.to_excel(writer,sheet_name='South No FL',startrow=5,startcol=0,index=False)
    fl=pmix(data,shopid=0,state=['FL'],week_min=1,week_max=49,sv='No',comp='Yes')
    fl.to_excel(writer,sheet_name='Florida',startrow=5,startcol=0,index=False)
    
    west=pmix(data,shopid=0,state=['AZ','CA','CO','OK','TX','UT'],week_min=1,week_max=49,sv='No',comp='Yes')
    west.to_excel(writer,sheet_name='West',startrow=5,startcol=0,index=False)
    
    wb=writer.book
    ws=writer.sheets['Philly']
    ws1=writer.sheets['Baltimore']
    ws2=writer.sheets['DC']
    ws3=writer.sheets['Pittsburgh']
    ws4=writer.sheets['HLLY']
    ws5=writer.sheets['WBS']
    ws6=writer.sheets['MID-NE']
    ws7=writer.sheets['Midwest']
    ws8=writer.sheets['South No FL']
    ws9=writer.sheets['Florida']
    ws10=writer.sheets['West']

    title='Ritas Franchise Company,LLC'
    text1='2024 Philadelphia PMIX'
    text2='2024 Baltimore PMIX'
    text3='2024 Washington PMIX'
    text4='2024 Pittsburgh PMIX'
    text5='2024 HLLY PMIX'
    text6='2024 Wilke-Barre/Scanton PMIX'
    text7='2024 Mid-Atlantic/Northeast Regions PMIX'
    text8='2024 Midwest Region PMIX'
    text9='2024 South Region(No Florida) PMIX'
    text10='2024 Florida PMIX'
    text11='2024 West Region PMIX'
    text12='Weeks 1-49 Comp Sales Only-No Special Venues'
    text13='Source Code: ritascoolnet_live tmp_raw_pdla'

    header_format=wb.add_format({'bold':True,
                                        'italic':True})
    dollar_format=wb.add_format({'num_format':'$#,##0'})
    perc_format=wb.add_format({'num_format':'0.0%'})
    vol_format=wb.add_format({'num_format':'#,##0'})
    border_format=wb.add_format({'top':2,'bottom':2,'left':2,'right':2})


    ws.conditional_format(xlsxwriter.utility.xl_range(5,0,len(philly)+5,len(philly.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws.write(0,1,title,header_format)
    ws.write(1,1,text1,header_format)
    ws.write(2,1,text12,header_format)
    ws.write(3,1,text13,header_format)
    ws.set_column('A:A',28)
    ws.set_column('B:B',40,dollar_format)
    ws.set_column('C:C',30,vol_format)
    ws.set_column('D:E',20,perc_format)
    ws.hide_gridlines(2)
    ws.insert_image('A1','Logo.png')

    ws1.conditional_format(xlsxwriter.utility.xl_range(5,0,len(balt)+5,len(balt.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws1.write(0,1,title,header_format)
    ws1.write(1,1,text2,header_format)
    ws1.write(2,1,text12,header_format)
    ws1.write(3,1,text13,header_format)
    ws1.set_column('A:A',28)
    ws1.set_column('B:B',40,dollar_format)
    ws1.set_column('C:C',30,vol_format)
    ws1.set_column('D:E',20,perc_format)
    ws1.hide_gridlines(2)
    ws1.insert_image('A1','Logo.png')

    ws2.conditional_format(xlsxwriter.utility.xl_range(5,0,len(dc)+5,len(dc.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws2.write(0,1,title,header_format)
    ws2.write(1,1,text3,header_format)
    ws2.write(2,1,text12,header_format)
    ws2.write(3,1,text13,header_format)
    ws2.set_column('A:A',28)
    ws2.set_column('B:B',40,dollar_format)
    ws2.set_column('C:C',30,vol_format)
    ws2.set_column('D:E',20,perc_format)
    ws2.hide_gridlines(2)
    ws2.insert_image('A1','Logo.png')

    ws3.conditional_format(xlsxwriter.utility.xl_range(5,0,len(pitt)+5,len(pitt.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws3.write(0,1,title,header_format)
    ws3.write(1,1,text4,header_format)
    ws3.write(2,1,text12,header_format)
    ws3.write(3,1,text13,header_format)
    ws3.set_column('A:A',28)
    ws3.set_column('B:B',40,dollar_format)
    ws3.set_column('C:C',30,vol_format)
    ws3.set_column('D:E',20,perc_format)
    ws3.hide_gridlines(2)
    ws3.insert_image('A1','Logo.png')

    ws4.conditional_format(xlsxwriter.utility.xl_range(5,0,len(hlly)+5,len(hlly.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws4.write(0,1,title,header_format)
    ws4.write(1,1,text5,header_format)
    ws4.write(2,1,text12,header_format)
    ws4.write(3,1,text13,header_format)
    ws4.set_column('A:A',28)
    ws4.set_column('B:B',40,dollar_format)
    ws4.set_column('C:C',30,vol_format)
    ws4.set_column('D:E',20,perc_format)
    ws4.hide_gridlines(2)
    ws4.insert_image('A1','Logo.png')

    ws5.conditional_format(xlsxwriter.utility.xl_range(5,0,len(wbs)+5,len(wbs.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws5.write(0,1,title,header_format)
    ws5.write(1,1,text6,header_format)
    ws5.write(2,1,text12,header_format)
    ws5.write(3,1,text13,header_format)
    ws5.set_column('A:A',28)
    ws5.set_column('B:B',40,dollar_format)
    ws5.set_column('C:C',30,vol_format)
    ws5.set_column('D:E',20,perc_format)
    ws5.hide_gridlines(2)
    ws5.insert_image('A1','Logo.png')

    ws6.conditional_format(xlsxwriter.utility.xl_range(5,0,len(mid)+5,len(mid.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws6.write(0,1,title,header_format)
    ws6.write(1,1,text7,header_format)
    ws6.write(2,1,text12,header_format)
    ws6.write(3,1,text13,header_format)
    ws6.set_column('A:A',28)
    ws6.set_column('B:B',40,dollar_format)
    ws6.set_column('C:C',30,vol_format)
    ws6.set_column('D:E',20,perc_format)
    ws6.hide_gridlines(2)
    ws6.insert_image('A1','Logo.png')

    ws7.conditional_format(xlsxwriter.utility.xl_range(5,0,len(mw)+5,len(mw.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws7.write(0,1,title,header_format)
    ws7.write(1,1,text8,header_format)
    ws7.write(2,1,text12,header_format)
    ws7.write(3,1,text13,header_format)
    ws7.set_column('A:A',28)
    ws7.set_column('B:B',40,dollar_format)
    ws7.set_column('C:C',30,vol_format)
    ws7.set_column('D:E',20,perc_format)
    ws7.hide_gridlines(2)
    ws7.insert_image('A1','Logo.png')

    ws8.conditional_format(xlsxwriter.utility.xl_range(5,0,len(south)+5,len(south.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws8.write(0,1,title,header_format)
    ws8.write(1,1,text1,header_format)
    ws8.write(2,1,text12,header_format)
    ws8.write(3,1,text13,header_format)
    ws8.set_column('A:A',28)
    ws8.set_column('B:B',40,dollar_format)
    ws8.set_column('C:C',30,vol_format)
    ws8.set_column('D:E',20,perc_format)
    ws8.hide_gridlines(2)
    ws8.insert_image('A1','Logo.png')

    ws9.conditional_format(xlsxwriter.utility.xl_range(5,0,len(fl)+5,len(fl.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws9.write(0,1,title,header_format)
    ws9.write(1,1,text10,header_format)
    ws9.write(2,1,text12,header_format)
    ws9.write(3,1,text13,header_format)
    ws9.set_column('A:A',28)
    ws9.set_column('B:B',40,dollar_format)
    ws9.set_column('C:C',30,vol_format)
    ws9.set_column('D:E',20,perc_format)
    ws9.hide_gridlines(2)
    ws9.insert_image('A1','Logo.png')

    ws10.conditional_format(xlsxwriter.utility.xl_range(5,0,len(west)+5,len(west.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws10.write(0,1,title,header_format)
    ws10.write(1,1,text11,header_format)
    ws10.write(2,1,text12,header_format)
    ws10.write(3,1,text13,header_format)
    ws10.set_column('A:A',28)
    ws10.set_column('B:B',40,dollar_format)
    ws10.set_column('C:C',30,vol_format)
    ws10.set_column('D:E',20,perc_format)
    ws10.hide_gridlines(2)
    ws10.insert_image('A1','Logo.png')

In [ ]:
all_data

# 2024 v 2023 Sales and Volume Growth

In [57]:
def growth(data=all_data,dma=None,coop=None,msa=None,shopid=None,week_min=1,
           week_max=None,state=None,sv=None,region=None,comp=None):
    '''
    Generate a pivot table summarizing sales and quantities YoY Growth for different filters.

    Parameters:
        data (pd.DataFrame): Dataset containing sales data.
        dma (list, optional): List of DMAs to filter by.
        coop (list, optional): List of CoOps to filter by.
        msa (str, optional): Substring to match in MSA names.
        shopid (list, optional): List of ShopIDs to filter by.
        state (list, optional): List of states to filter by.
        region (list, optional): List of regions to filter by.
        sv (list, optional): SV filter (default is '').
        comp (list, optional): Comp filter (default is '').
        week_min (int, optional): Minimum week number for filtering (default is 1).
        week_max (int, optional): Maximum week number for filtering (default is data's max week).

    Returns:
        pd.DataFrame: Pivot table summarizing sales and quantities by Year and, 
                      including percentages of YoY sales and quantity growth.
    
    '''
    
    # Set default week_max if not provided
    if week_max is None:
        week_max = data.Week.max()
    
    # Create a base filter
    base_filter = (data.Week.between(week_min, week_max))
    
    if dma:
        base_filter &= data.DMA.isin(dma)
    if coop:
        base_filter &= data.CoOpName.isin(coop)
    if msa:
        base_filter &= data.MSA.isin(msa)
    if shopid:
        base_filter &= data.ShopID.isin(shopid)
    if state:
        base_filter &= data.State.isin(state)
    if sv:
        base_filter &= (data.SpecialVenue==sv)
    if region:
        base_filter &= data.Region.isin(region)
    if comp:
        base_filter &= (data.Comps==comp)
        
    # Filter the data
    filtered_data = data[base_filter]

    # Check for empty filtered data
    if filtered_data.empty:
        return pd.DataFrame({'Message': ['No data found for the given filters']})
    
    # Calculate total sales and quantities
    total_sales = filtered_data.SalesMny.sum()
    total_qty = filtered_data.SalesQty.sum()
    
    #Defines the column names of the final Pivot Table
    column_names=['ProductSizeName','Sales_23','Sales_24','Units_Sold_23','Units_Sold_24']
    
    #Creates the Pivot Table Based off the condtions that were defined in the function
    yoy_growth=filtered_data.pivot_table(index='ProductSizeName',
                           columns='Year',
                           values=['SalesMny','SalesQty'],
                           aggfunc='sum',fill_value=0).reset_index()
    
    #Renames the columns of the pivot table
    yoy_growth.columns=column_names
    
    #Adds the Growth Columns to the Pivot Table
    yoy_growth['Sales_Growth%']=yoy_growth['Sales_24']/yoy_growth['Sales_23']-1
    yoy_growth['Unit_Growth%']=yoy_growth['Units_Sold_24']/yoy_growth['Units_Sold_23']-1
    
    # Aligns the columns correctlt
    yoy_growth=yoy_growth.iloc[:,[0,2,1,5,4,3,6]]
    
    # Replaces the NaN's, inf, and -inf with 0. This occurs when we try to divide by zero. Math says you can't do that
    yoy_growth=yoy_growth.replace([np.NaN,np.inf,-np.inf],0).sort_values(by='Sales_24',ascending=False)
    
    return(yoy_growth)

In [ ]:
growth(all_data).to_excel('All Week Test ProductSize.xlsx',index=False)

In [58]:
with pd.ExcelWriter('Test Product Size 2024-2023 Growth Week 1-49.xlsx',engine='xlsxwriter') as writer:
    philly=growth(shopid=0,dma=['Philadelphia'],week_min=1,week_max=49,sv='No',comp='Yes')\
    .sort_values(by=['Sales_24'],ascending=False)
    philly.to_excel(writer,sheet_name='Philly',startrow=5,startcol=0,index=False)
    balt=growth(shopid=0,dma=['Baltimore'],week_min=1,week_max=49,sv='No',comp='Yes')\
                    .sort_values(by=['Sales_24'],ascending=False)
    balt.to_excel(writer, sheet_name='Baltimore',startrow=5,startcol=0,index=False)
    dc=growth(shopid=0,dma=['Washington DC'],week_min=1,week_max=49,sv='No',comp='Yes')\
                    .sort_values(by=['Sales_24'],ascending=False)
    dc.to_excel(writer,sheet_name='DC',startrow=5,startcol=0,index=False)
    pitt=growth(shopid=0,dma=['Pittsburgh'],week_min=1,week_max=49,sv='No',comp='Yes')\
                    .sort_values(by=['Sales_24'],ascending=False)
    pitt.to_excel(writer,sheet_name='Pittsburgh',startrow=5,startcol=0,index=False)
    hlly=growth(shopid=0,dma=['Harrisburg-Lancaster-Lebanon-York'],week_min=1,week_max=49,sv='No',comp='Yes')\
                    .sort_values(by=['Sales_24'],ascending=False)
    hlly.to_excel(writer,sheet_name='HLLY',startrow=5,startcol=0,index=False)
    wbs=growth(shopid=0,dma=['Wilkes Barre-Scranton'],week_min=1,week_max=49,sv='No',comp='Yes')\
                    .sort_values(by=['Sales_24'],ascending=False)
    wbs.to_excel(writer,sheet_name='WBS',startrow=5,startcol=0,index=False)
    
    mid=growth(shopid=0,state=['CT','DC','DE','MA','MD','NJ','NY','PA','VA','WV'],week_min=1,week_max=49,sv='No',comp='Yes')\
                    .sort_values(by=['Sales_24'],ascending=False)
    mid.to_excel(writer,sheet_name='MID-NE',startrow=5,startcol=0,index=False)
    
    mw=growth(shopid=0,state=['IL','IN','KY','OH','MI','MN','MO'],week_min=1,week_max=49,sv='No',comp='Yes')\
                    .sort_values(by=['Sales_24'],ascending=False)
    mw.to_excel(writer,sheet_name='Midwest',startrow=5,startcol=0,index=False)
    
    south=growth(shopid=0,state=['SC',
           'GA','NC','TN','AL'],week_min=1,week_max=49,sv='No',comp='Yes')\
                    .sort_values(by=['Sales_24'],ascending=False)
    south.to_excel(writer,sheet_name='South No FL',startrow=5,startcol=0,index=False)
    fl=growth(shopid=0,state=['FL'],week_min=1,week_max=49,sv='No',comp='Yes')\
                    .sort_values(by=['Sales_24'],ascending=False)
    fl.to_excel(writer,sheet_name='Florida',startrow=5,startcol=0,index=False)
    
    west=growth(shopid=0,state=['AZ','CA','CO','OK','TX','UT'],week_min=1,week_max=49,sv='No',comp='Yes')\
                    .sort_values(by=['Sales_24'],ascending=False)
    west.to_excel(writer,sheet_name='West',startrow=5,startcol=0,index=False)

    wb=writer.book
    ws=writer.sheets['Philly']
    ws1=writer.sheets['Baltimore']
    ws2=writer.sheets['DC']
    ws3=writer.sheets['Pittsburgh']
    ws4=writer.sheets['HLLY']
    ws5=writer.sheets['WBS']
    ws6=writer.sheets['MID-NE']
    ws7=writer.sheets['Midwest']
    ws8=writer.sheets['South No FL']
    ws9=writer.sheets['Florida']
    ws10=writer.sheets['West']

    title='Ritas Franchise Company,LLC'
    text1='2024 Philadelphia Growth'
    text2='2024 Baltimore Growth'
    text3='2024 Washington Growth'
    text4='2024 Pittsburgh Growth'
    text5='2024 HLLY Growth'
    text6='2024 Wilke-Barre/Scanton Growth'
    text7='2024 Mid-Atlantic/Northeast Regions Growth'
    text8='2024 Midwest Region Growth'
    text9='2024 South Region(No Florida) Growth'
    text10='2024 Florida Growth'
    text11='2024 West Region Growth'
    text12='Weeks 9-49 Comp Sales Only-No Special Venues'
    text13='Source Code: ritascoolnet_live tmp_raw_pdla'

    header_format=wb.add_format({'bold':True,
                                        'italic':True})
    
    dollar_format=wb.add_format({'num_format':'$#,##0'})
    perc_format=wb.add_format({'num_format':'0.0%'})
    vol_format=wb.add_format({'num_format':'#,##0'})
    border_format=wb.add_format({'top':2,'bottom':2,'left':2,'right':2})
    
    ws.conditional_format(xlsxwriter.utility.xl_range(5,0,len(philly)+5,len(philly.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws.write(0,1,title,header_format)
    ws.write(1,1,text1,header_format)
    ws.write(2,1,text12,header_format)
    ws.write(3,1,text13,header_format)
    ws.set_column('A:A',28)
    ws.set_column('B:C',40,dollar_format)
    ws.set_column('D:D',30,perc_format)
    ws.set_column('E:F',20,vol_format)
    ws.set_column('G:G',30,perc_format)
    ws.hide_gridlines(2)
    ws.insert_image('A1','Logo.png')
    
    ws1.conditional_format(xlsxwriter.utility.xl_range(5,0,len(balt)+5,len(balt.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws1.write(0,1,title,header_format)
    ws1.write(1,1,text2,header_format)
    ws1.write(2,1,text12,header_format)
    ws1.write(3,1,text13,header_format)
    ws1.set_column('A:A',28)
    ws1.set_column('B:C',40,dollar_format)
    ws1.set_column('D:D',30,perc_format)
    ws1.set_column('E:F',20,vol_format)
    ws1.set_column('G:G',30,perc_format)
    ws1.hide_gridlines(2)
    ws1.insert_image('A1','Logo.png')

    ws2.conditional_format(xlsxwriter.utility.xl_range(5,0,len(dc)+5,len(dc.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws2.write(0,1,title,header_format)
    ws2.write(1,1,text3,header_format)
    ws2.write(2,1,text12,header_format)
    ws2.write(3,1,text13,header_format)
    ws2.set_column('A:A',28)
    ws2.set_column('B:C',40,dollar_format)
    ws2.set_column('D:D',30,perc_format)
    ws2.set_column('E:F',20,vol_format)
    ws2.set_column('G:G',30,perc_format)
    ws2.hide_gridlines(2)
    ws2.insert_image('A1','Logo.png')
    
    ws3.conditional_format(xlsxwriter.utility.xl_range(5,0,len(pitt)+5,len(pitt.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws3.write(0,1,title,header_format)
    ws3.write(1,1,text4,header_format)
    ws3.write(2,1,text12,header_format)
    ws3.write(3,1,text13,header_format)
    ws3.set_column('A:A',28)
    ws3.set_column('B:C',40,dollar_format)
    ws3.set_column('D:D',30,perc_format)
    ws3.set_column('E:F',20,vol_format)
    ws3.set_column('G:G',30,perc_format)
    ws3.hide_gridlines(2)
    ws3.insert_image('A1','Logo.png')
    
    ws4.conditional_format(xlsxwriter.utility.xl_range(5,0,len(hlly)+5,len(hlly.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws4.write(0,1,title,header_format)
    ws4.write(1,1,text5,header_format)
    ws4.write(2,1,text12,header_format)
    ws4.write(3,1,text13,header_format)
    ws4.set_column('A:A',28)
    ws4.set_column('B:C',40,dollar_format)
    ws4.set_column('D:D',30,perc_format)
    ws4.set_column('E:F',20,vol_format)
    ws4.set_column('G:G',30,perc_format)
    ws4.hide_gridlines(2)
    ws4.insert_image('A1','Logo.png')

    ws5.conditional_format(xlsxwriter.utility.xl_range(5,0,len(wbs)+5,len(wbs.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws5.write(0,1,title,header_format)
    ws5.write(1,1,text6,header_format)
    ws5.write(2,1,text12,header_format)
    ws5.write(3,1,text13,header_format)
    ws5.set_column('A:A',28)
    ws5.set_column('B:C',40,dollar_format)
    ws5.set_column('D:D',30,perc_format)
    ws5.set_column('E:F',20,vol_format)
    ws5.set_column('G:G',30,perc_format)
    ws5.hide_gridlines(2)
    ws5.insert_image('A1','Logo.png')

    ws6.conditional_format(xlsxwriter.utility.xl_range(5,0,len(mid)+5,len(mid.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws6.write(0,1,title,header_format)
    ws6.write(1,1,text7,header_format)
    ws6.write(2,1,text12,header_format)
    ws6.write(3,1,text13,header_format)
    ws6.set_column('A:A',28)
    ws6.set_column('B:C',40,dollar_format)
    ws6.set_column('D:D',30,perc_format)
    ws6.set_column('E:F',20,vol_format)
    ws6.set_column('G:G',30,perc_format)
    ws6.hide_gridlines(2)
    ws6.insert_image('A1','Logo.png')
    
    ws7.conditional_format(xlsxwriter.utility.xl_range(5,0,len(mw)+5,len(mw.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws7.write(0,1,title,header_format)
    ws7.write(1,1,text8,header_format)
    ws7.write(2,1,text12,header_format)
    ws7.write(3,1,text13,header_format)
    ws7.set_column('A:A',28)
    ws7.set_column('B:C',40,dollar_format)
    ws7.set_column('D:D',30,perc_format)
    ws7.set_column('E:F',20,vol_format)
    ws7.set_column('G:G',30,perc_format)
    ws7.hide_gridlines(2)
    ws7.insert_image('A1','Logo.png')

    ws8.conditional_format(xlsxwriter.utility.xl_range(5,0,len(south)+5,len(south.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws8.write(0,1,title,header_format)
    ws8.write(1,1,text9,header_format)
    ws8.write(2,1,text12,header_format)
    ws8.write(3,1,text13,header_format)
    ws8.set_column('A:A',28)
    ws8.set_column('B:C',40,dollar_format)
    ws8.set_column('D:D',30,perc_format)
    ws8.set_column('E:F',20,vol_format)
    ws8.set_column('G:G',30,perc_format)
    ws8.hide_gridlines(2)
    ws8.insert_image('A1','Logo.png')

    ws9.conditional_format(xlsxwriter.utility.xl_range(5,0,len(fl)+5,len(fl.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws9.write(0,1,title,header_format)
    ws9.write(1,1,text10,header_format)
    ws9.write(2,1,text12,header_format)
    ws9.write(3,1,text13,header_format)
    ws9.set_column('A:A',28)
    ws9.set_column('B:C',40,dollar_format)
    ws9.set_column('D:D',30,perc_format)
    ws9.set_column('E:F',20,vol_format)
    ws9.set_column('G:G',30,perc_format)
    ws9.hide_gridlines(2)
    ws9.insert_image('A1','Logo.png')

    ws10.conditional_format(xlsxwriter.utility.xl_range(5,0,len(west)+5,len(west.columns)-1),
                                      {'type': 'no_errors', 'format': border_format})
    ws10.write(0,1,title,header_format)
    ws10.write(1,1,text11,header_format)
    ws10.write(2,1,text12,header_format)
    ws10.write(3,1,text13,header_format)
    ws10.set_column('A:A',28)
    ws10.set_column('B:C',40,dollar_format)
    ws10.set_column('D:D',30,perc_format)
    ws10.set_column('G:G',30,perc_format)
    ws10.set_column('E:F',20,vol_format)
    ws10.hide_gridlines(2)
    ws10.insert_image('A1','Logo.png')

# Original PMIX Function- Too Much Repitetion

In [ ]:
#     data=all_data[all_data.StartDate.dt.year==2024]
#     def pmix(dma=[],coop=[],msa='',shopid=[],week_min=1,week_max=data.Week.max(),state=[],sv='',region=[],comp=''):
#         if shopid:
#             sales=data[(data.ShopID.isin(shopid))&(data.Week.between(week_min,week_max))&(data.SV==sv)&(data.Comps==comp)].SalesMny.sum()
#             qty=data[(data.ShopID.isin(shopid))&(data.Week.between(week_min,week_max))&(data.SV==sv)&(data.Comps==comp)].SalesQty.sum()
#             item24=data[(data.ShopID.isin(shopid))&(data.Week.between(week_min,week_max))&(data.SV==sv)&(data.Comps==comp)].pivot_table(index='ProductTypeName',
#                                                values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
#             item24['Sales%']=item24.SalesMny/sales
#             item24['Qty%']=item24.SalesQty/qty
#         if dma:
#             sales=data[(data.DMA.isin(dma))&(data.Week.between(week_min,week_max))&(data.SV==sv)&(data.Comps==comp)].SalesMny.sum()
#             qty=data[(data.DMA.isin(dma))&(data.Week.between(week_min,week_max))&(data.SV==sv)&(data.Comps==comp)].SalesQty.sum()
#             item24=data[(data.DMA.isin(dma))&(data.Week.between(week_min,week_max))&(data.SV==sv)&(data.Comps==comp)].pivot_table(index='ProductTypeName',
#                                                    values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
#             item24['Sales%']=item24.SalesMny/sales
#             item24['Qty%']=item24.SalesQty/qty
#         if coop:
#             sales=data[(data.CoOpName.isin(coop))&(data.Week.between(week_min,week_max))&(data.SV==sv)&(data.Comps==comp)].SalesMny.sum()
#             qty=data[(data.CoOpName.isin(coop))&(data.Week.between(week_min,week_max))&(data.SV==sv)&(data.Comps==comp)].SalesQty.sum()
#             item24=data[(data.CoOpName.isin(coop))&(data.Week.between(week_min,week_max))&(data.SV==sv)&(data.Comps==comp)].pivot_table(index='ProductTypeName',
#                                                    values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
#             item24['Sales%']=item24.SalesMny/sales
#             item24['Qty%']=item24.SalesQty/qty
#         if msa:
#             sales=data[(data.MSAName.str.contains(msa))&(data.Week.between(week_min,week_max))&(data.SV==sv)&(data.Comps==comp)].SalesMny.sum()
#             qty=data[(data.MSAName.str.contains(msa))&(data.Week.between(week_min,week_max))&(data.SV==sv)&(data.Comps==comp)].SalesQty.sum()
#             item24=data[(data.MSAName.str.contains(msa))&(data.Week.between(week_min,week_max))&(data.SV==sv)&(data.Comps==comp)].pivot_table(
#                 index='ProductTypeName',
#                 values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
#             item24['Sales%']=item24.SalesMny/sales
#             item24['Qty%']=item24.SalesQty/qty
#         if state:
#             sales=data[(data.State.isin(state))&(data.Week.between(week_min,week_max))&(data.SV==sv)&(data.Comps==comp)].SalesMny.sum()
#             qty=data[(data.State.isin(state))&(data.Week.between(week_min,week_max))&(data.SV==sv)&(data.Comps==comp)].SalesQty.sum()
#             item24=data[(data.State.isin(state))&(data.Week.between(week_min,week_max))&(data.SV==sv)&(data.Comps==comp)].pivot_table(
#                 index='ProductTypeName',
#                 values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
#             item24['Sales%']=item24.SalesMny/sales
#             item24['Qty%']=item24.SalesQty/qty
#         if region:
#             sales=data[(data.Region.isin(region))&(data.Week.between(week_min,week_max))&(data.SV==sv)&(data.Comps==comp)].SalesMny.sum()
#             qty=data[(data.Region.isin(region))&(data.Week.between(week_min,week_max))&(data.SV==sv)&(data.Comps==comp)].SalesQty.sum()
#             item24=data[(data.Region.isin(region))&(data.Week.between(week_min,week_max))&(data.SV==sv)&(data.Comps==comp)].pivot_table(
#                 index='ProductTypeName',
#                 values=['SalesMny','SalesQty'],aggfunc='sum').reset_index()
#             item24['Sales%']=item24.SalesMny/sales
#             item24['Qty%']=item24.SalesQty/qty
#         return(item24)

# Orginal Growth Function- Too Much Repetition

In [ ]:
# def growth(dma=[],coop=[],msa='',shopid=[],week_min=1,week_max=all_data.Week.max(),state=[],sv='',region=[],comp=''):
#     column_names=['ProductTypeName','Sales_23','Sales_24','Units_Sold_23','Units_Sold_24']
#     if shopid:
#         item23=all_data[(all_data.ShopID.isin(shopid))&(all_data.Week.between(week_min,week_max))&(all_data.SV==sv)&
#                         (all_data.Comps==comp)].pivot_table(index='ProductTypeName',columns='Year',
#                                                values=['SalesMny','SalesQty'],aggfunc='sum',fill_value=0).reset_index()
#         item23.columns=column_names
#         item23=item23.iloc[:,[0,2,1,4,3]]
#         item23['Sales_Growth%']=item23['Sales_24']/item23['Sales_23']-1
#         item23['Unit_Growth%']=item23['Units_Sold_24']/item23['Units_Sold_23']-1
#         item23=item23.iloc[:,[0,1,2,5,3,4,6]]
#         item23.replace([np.inf,-np.inf],inplace=True)
#         item23.fillna(0,inplace=True)
#     elif shopid==0:
#         if dma:
#             item23=all_data[(all_data.DMA.isin(dma))&(all_data.Week.between(week_min,week_max))&(all_data.SV==sv)&(all_data.Comps==comp)].pivot_table(index='ProductTypeName',columns='Year',
#                                                    values=['SalesMny','SalesQty'],aggfunc='sum',fill_value=0).reset_index()
#             item23.columns=column_names
#             item23=item23.iloc[:,[0,2,1,4,3]]
#             item23['Sales_Growth%']=item23['Sales_24']/item23['Sales_23']-1
#             item23['Unit_Growth%']=item23['Units_Sold_24']/item23['Units_Sold_23']-1
#             item23=item23.iloc[:,[0,1,2,5,3,4,6]]
#             item23.replace([np.inf,-np.inf],inplace=True)
#             item23.fillna(0,inplace=True)
#         if coop:
#             item23=all_data[(all_data.CoOpName.isin(coop))&(all_data.Week.between(week_min,week_max))&(all_data.SV==sv)&(all_data.Comps==comp)].pivot_table(index='ProductTypeName',columns='Year',
#                                                    values=['SalesMny','SalesQty'],aggfunc='sum',fill_value=0).reset_index()
#             item23.columns=column_names
#             item23=item23.iloc[:,[0,2,1,4,3]]
#             item23['Sales_Growth%']=item23['Sales_24']/item23['Sales_23']-1
#             item23['Unit_Growth%']=item23['Units_Sold_24']/item23['Units_Sold_23']-1
#             item23=item23.iloc[:,[0,1,2,5,3,4,6]]
#             item23.replace([np.inf,-np.inf,NaN],inplace=True)
#             item23.fillna(0,inplace=True)
#         if msa:
#             item23=all_data[(all_data.MSAName.str.contains(msa))&(all_data.Week.between(week_min,week_max))&(all_data.SV==sv)&(all_data.Comps==comp)].pivot_table(
#                 index='ProductTypeName',columns='Year',
#                 values=['SalesMny','SalesQty'],aggfunc='sum',fill_value=0).reset_index()
#             item23.columns=column_names
#             item23=item23.iloc[:,[0,2,1,4,3]]
#             item23['Sales_Growth%']=item23['Sales_24']/item23['Sales_23']-1
#             item23['Unit_Growth%']=item23['Units_Sold_24']/item23['Units_Sold_23']-1
#             item23=item23.iloc[:,[0,1,2,5,3,4,6]]
#             item23.replace([np.inf,-np.inf],inplace=True)
#             item23.fillna(0,inplace=True)
#         if state:
#             item23=all_data[(all_data.State.isin(state))&(all_data.Week.between(week_min,week_max))&(all_data.SV==sv)&(all_data.Comps==comp)].pivot_table(
#                 index='ProductTypeName',columns='Year',
#                 values=['SalesMny','SalesQty'],aggfunc='sum',fill_value=0).reset_index()
#             item23.columns=column_names
#             item23=item23.iloc[:,[0,2,1,4,3]]
#             item23['Sales_Growth%']=item23['Sales_24']/item23['Sales_23']-1
#             item23['Unit_Growth%']=item23['Units_Sold_24']/item23['Units_Sold_23']-1
#             item23=item23.iloc[:,[0,1,2,5,3,4,6]]
#             item23.replace([np.inf,-np.inf],inplace=True)
#             item23.fillna(0,inplace=True)
#         if region:
#             item23=all_data[(all_data.Region.isin(region))&(all_data.Week.between(week_min,week_max))&(all_data.SV==sv)&(all_data.Comps==comp)].pivot_table(
#                 index='ProductTypeName',columns='Year',
#                 values=['SalesMny','SalesQty'],aggfunc='sum',fill_value=0).reset_index()
#             item23.columns=column_names
#             item23=item23.iloc[:,[0,2,1,4,3]]
#             item23['Sales_Growth%']=item23['Sales_24']/item23['Sales_23']-1
#             item23['Unit_Growth%']=item23['Units_Sold_24']/item23['Units_Sold_23']-1
#             item23=item23.iloc[:,[0,1,2,5,3,4,6]]
#             item23.replace([np.inf,-np.inf],inplace=True)
#             item23.fillna(0,inplace=True)
#     return(item23)