# John Harned Work Sample
## This code is meant to show my competence in ETL, data manipulation and reporting

   1. We first import the necessary libraries
   2. We connect to our SQL servers to query the data tables needed
   3. Simple data manipulation- cleaning the data, merging tables together, and verification
   4. Define the function- A YoY sales and volume Growth Function with specific parameters that End Users can call to view
       specific time period, location, or store type
   5. Implementation of Growth Function that produces clean and accruate reports in Excel for End Users to analyze and     visualize
   6. Define a function- A YoY sales and average check comparison using Sales and Guest Counts. End Users can enter in their specifc parameters to geta detailed brekadown of shop performance
   7. Implentation of Sales and Avg Check Function. Clean and accurate reports in Excel for End-Users to perform thier own analysis or for their own reporting

In [1]:
import pandas as pd
import os
import numpy as np
import pyodbc as odbc
from datetime import date,timedelta
import warnings
warnings.filterwarnings('ignore')
os.chdir(r'G:\FinanceReports\2024\Wk42')

In [2]:
# Names the needed driver, server name, and database
driver_name='SQL Server'
server_name='10.0.1.218'
database='ritascoolnet_live'
#Creates the connection string
connection_string=f"""
DRIVER={{{driver_name}}};
SERVER={server_name};
DATABASE={database};
Trust_Connection=yes"""
#Creates the Connection to SQL Server
connection=odbc.connect(connection_string)
print(connection)
data=pd.read_sql_query('''SELECT *
  FROM [ritas_bi].[dbo].[tmp_raw_plda]
  WHERE YEAR(StartDate)=2024
  ORDER BY Week DESC''',connection)
data1=pd.read_sql_query('''SELECT *
  FROM [ritas_bi].[dbo].[tmp_raw_plda]
  WHERE YEAR(StartDate)=2023
  ORDER BY Week DESC''',connection)
# data2=pd.read_sql_query('''SELECT *
#   FROM [ritas_bi].[dbo].[tmp_raw_pldb]
#   WHERE YEAR(StartDate)=2021''',connection)
data3=pd.read_sql_query('''Select intstoreid,RitasID as ShopID, FC,CoolNetGroup,LegacyStoreType,State,MSAName,DMA,StoreName as ShopName,StoreStatus,[Special Venue] as SV,SeasonClose,[Parent Shop #] as ParentID from ritascoolnet_live.dbo.vShopDetail''',connection)

<pyodbc.Connection object at 0x000002072E011D30>

In [3]:
#Reads in the Guest Count
gc_1=pd.read_sql_query(
    '''SELECT intWeek as Week,intYear as Year,RecordNumber as ShopID,WeeklyTransactions as GC  from ritascoolnet_live.dbo.tblFinancialSummary2023 Where intYear=2023''',connection)
gc_2=pd.read_sql_query(
    '''SELECT intWeek as Week,intYear as Year,RecordNumber as ShopID,WeeklyTransactions as GC  from ritascoolnet_live.dbo.tblFinancialSummary2024''',connection)

In [4]:
#Combines the 2024 and 2023 Guest Counts
gc_total=pd.concat([gc_1,gc_2])
#Converts ShopID to integer
gc_total['ShopID']=gc_total.ShopID.astype('int')

In [5]:
# Adds the Year Column to the dataframe
data['Year']=data.StartDate.dt.year
data1['Year']=data1.StartDate.dt.year
all_data=pd.concat([data,data1]) # combines dataframes into one dataframe
# all_data=all_data[all_data.Week<=23] # filters on Weeks 1-23 onlu
# all_data.Week.max() # verification

In [6]:
all_data.SalesMny.sum()

373727135.6433001

In [7]:
ad=all_data.pivot_table(index=['ShopID'],columns='Year',values='SalesMny',aggfunc='sum',fill_value=0).reset_index() #Creates
# pivot table by ShopID as the row, Year as the columns and sum of sales as the values
comps=ad[(ad[2023]>0)&(ad[2024]>0)] # filters out zeros in both columns to get comp sales
comps['Comps']='Yes' # adds a new column called comp with all values assign a Yes label 
all_data=all_data.merge(comps[['ShopID','Comps']],on='ShopID',how='left') #left join on ShopID to add Comps to dataframe
all_data.SalesMny.sum() # verification

373727135.6433001

In [8]:
all_data['Comps']=all_data.Comps.fillna('No') # fills NaN with No. These are not comp shops

In [9]:
data4=data3.sort_values(by='ShopID').drop_duplicates(subset='ParentID',keep='first') # Shop detail information

In [10]:
all_data=all_data.merge(data4[['ShopID','DMA','SV','MSAName','FC']],how='left',on='ShopID').drop_duplicates(keep='first') # left join
# to bring over shop information to all_data dataframe
all_data.SalesMny.sum() # verification

373727135.6433001

In [11]:
all_data.CoOpName=all_data.CoOpName.fillna('LSM')

In [12]:
# Creates function that will allow user to enter in parameters to view sales and volume growth for 2024 vs 2023.
# Users can view this by shop, DMA, CoOp, state or region
# Users can also choose to veiw data by timeframe and whether they want Special Venues to be included in the analysis
# or whether the user wants to veiw Comp shops only

def growth(dma=[],coop=[],msa='',shopid=[],week_min=1,week_max=all_data.Week.max(),state=[],sv='',region=[],comp=''):
    column_names=['ProductTypeName','Sales_23','Sales_24','Units_Sold_23','Units_Sold_24']
    if shopid:
        item23=all_data[(all_data.ShopID.isin(shopid))&(all_data.Week.between(week_min,week_max))&(all_data.SV==sv)&(all_data.Comps==comp)].pivot_table(index='ProductTypeName',columns='Year',
                                               values=['SalesMny','SalesQty'],aggfunc='sum',fill_value=0).reset_index()
        item23.columns=column_names
        item23=item23.iloc[:,[0,2,1,4,3]]
        item23['Sales_Growth%']=item23['Sales_24']/item23['Sales_23']-1
        item23['Unit_Growth%']=item23['Units_Sold_24']/item23['Units_Sold_23']-1
        item23=item23.iloc[:,[0,1,2,5,3,4,6]]
        item23.replace([np.inf,-np.inf],inplace=True)
        item23.fillna(0,inplace=True)
    elif shopid==0:
        if dma:
            item23=all_data[(all_data.DMA.isin(dma))&(all_data.Week.between(week_min,week_max))&(all_data.SV==sv)&(all_data.Comps==comp)].pivot_table(index='ProductTypeName',columns='Year',
                                                   values=['SalesMny','SalesQty'],aggfunc='sum',fill_value=0).reset_index()
            item23.columns=column_names
            item23=item23.iloc[:,[0,2,1,4,3]]
            item23['Sales_Growth%']=item23['Sales_24']/item23['Sales_23']-1
            item23['Unit_Growth%']=item23['Units_Sold_24']/item23['Units_Sold_23']-1
            item23=item23.iloc[:,[0,1,2,5,3,4,6]]
            item23.replace([np.inf,-np.inf],inplace=True)
            item23.fillna(0,inplace=True)
        if coop:
            item23=all_data[(all_data.CoOpName.isin(coop))&(all_data.Week.between(week_min,week_max))&(all_data.SV==sv)&(all_data.Comps==comp)].pivot_table(index='ProductTypeName',columns='Year',
                                                   values=['SalesMny','SalesQty'],aggfunc='sum',fill_value=0).reset_index()
            item23.columns=column_names
            item23=item23.iloc[:,[0,2,1,4,3]]
            item23['Sales_Growth%']=item23['Sales_24']/item23['Sales_23']-1
            item23['Unit_Growth%']=item23['Units_Sold_24']/item23['Units_Sold_23']-1
            item23=item23.iloc[:,[0,1,2,5,3,4,6]]
            item23.replace([np.inf,-np.inf],inplace=True)
            item23.fillna(0,inplace=True)
        if msa:
            item23=all_data[(all_data.MSAName.str.contains(msa))&(all_data.Week.between(week_min,week_max))&(all_data.SV==sv)&(all_data.Comps==comp)].pivot_table(
                index='ProductTypeName',columns='Year',
                values=['SalesMny','SalesQty'],aggfunc='sum',fill_value=0).reset_index()
            item23.columns=column_names
            item23=item23.iloc[:,[0,2,1,4,3]]
            item23['Sales_Growth%']=item23['Sales_24']/item23['Sales_23']-1
            item23['Unit_Growth%']=item23['Units_Sold_24']/item23['Units_Sold_23']-1
            item23=item23.iloc[:,[0,1,2,5,3,4,6]]
            item23.replace([np.inf,-np.inf],inplace=True)
            item23.fillna(0,inplace=True)
        if state:
            item23=all_data[(all_data.State.isin(state))&(all_data.Week.between(week_min,week_max))&(all_data.SV==sv)&(all_data.Comps==comp)].pivot_table(
                index='ProductTypeName',columns='Year',
                values=['SalesMny','SalesQty'],aggfunc='sum',fill_value=0).reset_index()
            item23.columns=column_names
            item23=item23.iloc[:,[0,2,1,4,3]]
            item23['Sales_Growth%']=item23['Sales_24']/item23['Sales_23']-1
            item23['Unit_Growth%']=item23['Units_Sold_24']/item23['Units_Sold_23']-1
            item23=item23.iloc[:,[0,1,2,5,3,4,6]]
            item23.replace([np.inf,-np.inf],inplace=True)
            item23.fillna(0,inplace=True)
        if region:
            item23=all_data[(all_data.Region.isin(region))&(all_data.Week.between(week_min,week_max))&(all_data.SV==sv)&(all_data.Comps==comp)].pivot_table(
                index='ProductTypeName',columns='Year',
                values=['SalesMny','SalesQty'],aggfunc='sum',fill_value=0).reset_index()
            item23.columns=column_names
            item23=item23.iloc[:,[0,2,1,4,3]]
            item23['Sales_Growth%']=item23['Sales_24']/item23['Sales_23']-1
            item23['Unit_Growth%']=item23['Units_Sold_24']/item23['Units_Sold_23']-1
            item23=item23.iloc[:,[0,1,2,5,3,4,6]]
            item23.replace([np.inf,-np.inf],inplace=True)
            item23.fillna(0,inplace=True)
    return(item23)

In [13]:
growth(shopid=0,state=['MD'],comp='No',sv='No')

ValueError: Length mismatch: Expected axis has 1 elements, new values have 5 elements

In [ ]:
# implementation of define growth function

writer=pd.ExcelWriter('2024-2023 Growth Week 9-23.xlsx')
growth(shopid=0,dma=['Philadelphia'],week_min=9,week_max=23,sv='No',comp='Yes')\
.sort_values(by=['Sales_24'],ascending=False).to_excel(writer,sheet_name='Philly',startrow=5,startcol=0,index=False)
growth(shopid=0,dma=['Baltimore'],week_min=9,week_max=213,sv='No',comp='Yes')\
                .sort_values(by=['Sales_24'],ascending=False).to_excel(writer, sheet_name='Baltimore',startrow=5,startcol=0,index=False)
growth(shopid=0,dma=['Washington DC'],week_min=9,week_max=23,sv='No',comp='Yes')\
                .sort_values(by=['Sales_24'],ascending=False).to_excel(writer,sheet_name='DC',startrow=5,startcol=0,index=False)
growth(shopid=0,dma=['Pittsburgh'],week_min=9,week_max=23,sv='No',comp='Yes')\
                .sort_values(by=['Sales_24'],ascending=False).to_excel(writer,sheet_name='Pittsburgh',startrow=5,startcol=0,index=False)
growth(shopid=0,dma=['Harrisburg-Lancaster-Lebanon-York'],week_min=9,week_max=23,sv='No',comp='Yes')\
                .sort_values(by=['Sales_24'],ascending=False).to_excel(writer,sheet_name='HLLY',startrow=5,startcol=0,index=False)
growth(shopid=0,dma=['Wilkes Barre-Scranton'],week_min=9,week_max=23,sv='No',comp='Yes')\
                .sort_values(by=['Sales_24'],ascending=False).to_excel(writer,sheet_name='WBS',startrow=5,startcol=0,index=False)
growth(shopid=0,region=['Mid-Atlantic',
       'Northeast'],week_min=9,week_max=23,sv='No',comp='Yes')\
                .sort_values(by=['Sales_24'],ascending=False).to_excel(writer,sheet_name='Mid-Atl & NE',startrow=5,startcol=0,index=False)
growth(shopid=0,region=['Midwest'],week_min=9,week_max=21,sv='No',comp='Yes')\
                .sort_values(by=['Sales_24'],ascending=False).to_excel(writer,sheet_name='Midwest',startrow=5,startcol=0,index=False)
growth(shopid=0,state=['SC',
       'GA','NC','TN','AL'],week_min=9,week_max=23,sv='No',comp='Yes')\
                .sort_values(by=['Sales_24'],ascending=False).to_excel(writer,sheet_name='South No FL',startrow=5,startcol=0,index=False)
growth(shopid=0,state=['FL'],week_min=9,week_max=23,sv='No',comp='Yes')\
                .sort_values(by=['Sales_24'],ascending=False).to_excel(writer,sheet_name='Florida',startrow=5,startcol=0,index=False)
growth(shopid=0,region=['West'],week_min=9,week_max=23,sv='No',comp='Yes')\
                .sort_values(by=['Sales_24'],ascending=False).to_excel(writer,sheet_name='West',startrow=5,startcol=0,index=False)

# Formatting report to Excel
wb=writer.book
ws=writer.sheets['Philly']
ws1=writer.sheets['Baltimore']
ws2=writer.sheets['DC']
ws3=writer.sheets['Pittsburgh']
ws4=writer.sheets['HLLY']
ws5=writer.sheets['WBS']
ws6=writer.sheets['Mid-Atl & NE']
ws7=writer.sheets['Midwest']
ws8=writer.sheets['South No FL']
ws9=writer.sheets['Florida']
ws10=writer.sheets['West']

title='Ritas Franchise Company,LLC'
text1='2024 Philadelphia Growth'
text2='2024 Baltimore Growth'
text3='2024 Washington Growth'
text4='2024 Pittsburgh Growth'
text5='2024 HLLY Growth'
text6='2024 Wilke-Barre/Scanton Growth'
text7='2024 Mid-Atlantic & Northeast Regions Growth'
text8='2024 Midwest Region Growth'
text9='2024 South Region(No Florida) Growth'
text10='2024 Florida Growth'
text11='2024 West Region Growth'
text12='Weeks 9-21'
text13='Source Code: ritascoolnet_live tmp_raw_pdla'
header_format=wb.add_format({'bold':True,
                                    'italic':True,
                                    'border':2,
                                    'bg_color':'#2898cc','color':'white'})
dollar_format=wb.add_format({'num_format':'$#,##0.00'})
perc_format=wb.add_format({'num_format':'0.0%'})
vol_format=wb.add_format({'num_format':'#,##0'})
ws.write(0,1,title,header_format)
ws.write(1,1,text1,header_format)
ws.write(2,1,text12,header_format)
ws.write(3,1,text13,header_format)
ws.set_column('A:A',28)
ws.set_column('B:C',40,dollar_format)
ws.set_column('D:D',30,perc_format)
ws.set_column('E:F',20,vol_format)
ws.set_column('G:G',30,perc_format)

ws1.write(0,1,title,header_format)
ws1.write(1,1,text2,header_format)
ws1.write(2,1,text12,header_format)
ws1.write(3,1,text13,header_format)
ws1.set_column('A:A',28)
ws1.set_column('B:C',40,dollar_format)
ws1.set_column('D:D',30,perc_format)
ws1.set_column('E:F',20,vol_format)
ws1.set_column('G:G',30,perc_format)

ws2.write(0,1,title,header_format)
ws2.write(1,1,text3,header_format)
ws2.write(2,1,text12,header_format)
ws2.write(3,1,text13,header_format)
ws2.set_column('A:A',28)
ws2.set_column('B:C',40,dollar_format)
ws2.set_column('D:D',30,perc_format)
ws2.set_column('E:F',20,vol_format)
ws2.set_column('G:G',30,perc_format)

ws3.write(0,1,title,header_format)
ws3.write(1,1,text4,header_format)
ws3.write(2,1,text12,header_format)
ws3.write(3,1,text13,header_format)
ws3.set_column('A:A',28)
ws3.set_column('B:C',40,dollar_format)
ws3.set_column('D:D',30,perc_format)
ws3.set_column('E:F',20,vol_format)
ws3.set_column('G:G',30,perc_format)

ws4.write(0,1,title,header_format)
ws4.write(1,1,text5,header_format)
ws4.write(2,1,text12,header_format)
ws4.write(3,1,text13,header_format)
ws4.set_column('A:A',28)
ws4.set_column('B:C',40,dollar_format)
ws4.set_column('D:D',30,perc_format)
ws4.set_column('E:F',20,vol_format)
ws4.set_column('G:G',30,perc_format)

ws5.write(0,1,title,header_format)
ws5.write(1,1,text6,header_format)
ws5.write(2,1,text12,header_format)
ws5.write(3,1,text13,header_format)
ws5.set_column('A:A',28)
ws5.set_column('B:C',40,dollar_format)
ws5.set_column('D:D',30,perc_format)
ws5.set_column('E:F',20,vol_format)
ws5.set_column('G:G',30,perc_format)

ws6.write(0,1,title,header_format)
ws6.write(1,1,text7,header_format)
ws6.write(2,1,text12,header_format)
ws6.write(3,1,text13,header_format)
ws6.set_column('A:A',28)
ws6.set_column('B:C',40,dollar_format)
ws6.set_column('D:D',30,perc_format)
ws6.set_column('E:F',20,vol_format)
ws6.set_column('G:G',30,perc_format)

ws7.write(0,1,title,header_format)
ws7.write(1,1,text8,header_format)
ws7.write(2,1,text12,header_format)
ws7.write(3,1,text13,header_format)
ws7.set_column('A:A',28)
ws7.set_column('B:C',40,dollar_format)
ws7.set_column('D:D',30,perc_format)
ws7.set_column('E:F',20,vol_format)
ws7.set_column('G:G',30,perc_format)

ws8.write(0,1,title,header_format)
ws8.write(1,1,text9,header_format)
ws8.write(2,1,text12,header_format)
ws8.write(3,1,text13,header_format)
ws8.set_column('A:A',28)
ws8.set_column('B:C',40,dollar_format)
ws8.set_column('D:D',30,perc_format)
ws8.set_column('E:F',20,vol_format)
ws8.set_column('G:G',30,perc_format)

ws9.write(0,1,title,header_format)
ws9.write(1,1,text10,header_format)
ws9.write(2,1,text12,header_format)
ws9.write(3,1,text13,header_format)
ws9.set_column('A:A',28)
ws9.set_column('B:C',40,dollar_format)
ws9.set_column('D:D',30,perc_format)
ws9.set_column('E:F',20,vol_format)
ws9.set_column('G:G',30,perc_format)

ws10.write(0,1,title,header_format)
ws10.write(1,1,text11,header_format)
ws10.write(2,1,text12,header_format)
ws10.write(3,1,text13,header_format)
ws10.set_column('A:A',28)
ws10.set_column('B:C',40,dollar_format)
ws10.set_column('D:D',30,perc_format)
ws10.set_column('G:G',30,perc_format)
ws10.set_column('E:F',20,vol_format)


writer.close()

# 2024 v 2023 Sales And Check Growth

In [ ]:
def sales_gc(coop=[],fc=[],dma=[],week_min=1,week_max=all_data.Week.max(),state=[],sv='',region=[],comp=''):
    test=all_data.fillna('Blank').groupby(['Year','Week','State','Region','CoOpName','SV','Comps','ShopID','FC','DMA'])['SalesMny'].sum().reset_index()\
    .merge(gc_total,on=['Year','Week','ShopID'],how='left').drop_duplicates(
    subset=['Year','Week','State','CoOpName','SV','Region','Comps','ShopID','FC','DMA'],keep='first')
    test.GC.fillna(0,inplace=True)
    if coop:
        test_piv=test[(test.CoOpName.isin(coop))&(test.SV==sv)&(test.Week.between(week_min,week_max))&(test.Comps==comp)]\
        .pivot_table(columns='Year',values=['SalesMny','GC'],aggfunc='sum')
        test_piv=test_piv[[2024,2023]]
        test_piv['Growth']=test_piv.iloc[:,0]/test_piv.iloc[:,1]-1
    if state:
        test_piv=test[(test.State.isin(state))&(test.SV==sv)&(test.Week.between(week_min,week_max))&(test.Comps==comp)]\
        .pivot_table(columns='Year',values=['SalesMny','GC'],aggfunc='sum')
        test_piv=test_piv[[2024,2023]]
        test_piv['Growth']=test_piv.iloc[:,0]/test_piv.iloc[:,1]-1
    if region:
        test_piv=test[(test.Region.isin(region))&(test.SV==sv)&(test.Week.between(week_min,week_max))&(test.Comps==comp)]\
        .pivot_table(columns='Year',values=['SalesMny','GC'],aggfunc='sum')
        test_piv=test_piv[[2024,2023]]
        test_piv['Growth']=test_piv.iloc[:,0]/test_piv.iloc[:,1]-1
    if fc:
        test_piv=test[(test.FC.isin(fc))&(test.SV==sv)&(test.Week.between(week_min,week_max))&(test.Comps==comp)]\
        .pivot_table(columns='Year',values=['SalesMny','GC'],aggfunc='sum')
        test_piv=test_piv[[2024,2023]]
        test_piv['Growth']=test_piv.iloc[:,0]/test_piv.iloc[:,1]-1
    if dma:
        test_piv=test[(test.DMA.isin(dma))&(test.SV==sv)&(test.Week.between(week_min,week_max))&(test.Comps==comp)]\
        .pivot_table(columns='Year',values=['SalesMny','GC'],aggfunc='sum')
        test_piv=test_piv[[2024,2023]]
        test_piv['Growth']=test_piv.iloc[:,0]/test_piv.iloc[:,1]-1
        
    return(test_piv)

In [ ]:
    writer=pd.ExcelWriter('2024-2023 Sales & GC Growth Week 9-23.xlsx')
    sales_gc(coop=['CO-OP PH/WI/TR'],week_min=9,week_max=23,sv='No',comp='Yes')\
    .to_excel(writer,sheet_name='Philly',startrow=5,startcol=0)
    sales_gc(coop=['CO-OP BALTI'],week_min=9,week_max=23,sv='No',comp='Yes')\
    .to_excel(writer,sheet_name='Baltimore',startrow=5,startcol=0)
    sales_gc(coop=['CO-OP WASHI'],week_min=9,week_max=23,sv='No',comp='Yes')\
    .to_excel(writer,sheet_name='DC',startrow=5,startcol=0)
    sales_gc(coop=['CO-OP BALTI'],week_min=9,week_max=23,sv='No',comp='Yes')\
    .to_excel(writer,sheet_name='Baltimore',startrow=5,startcol=0)
    sales_gc(coop=['CO-OP PITTS'],week_min=9,week_max=23,sv='No',comp='Yes')\
    .to_excel(writer,sheet_name='Pittsburgh',startrow=5,startcol=0)
    sales_gc(coop=['CO-OP YORK','CO-OP LANCA','CO-OP','CO-OP HARRI'],week_min=9,week_max=23,sv='No',comp='Yes')\
    .to_excel(writer,sheet_name='HLLY',startrow=5,startcol=0)
    sales_gc(dma=['Wilkes Barre-Scranton'],week_min=9,week_max=23,sv='No',comp='Yes')\
    .to_excel(writer,sheet_name='WBS',startrow=5,startcol=0)
    sales_gc(region=['Mid-Atlantic','Northeast'],week_min=9,week_max=23,sv='No',comp='Yes')\
    .to_excel(writer,sheet_name='Mid-Atl & NE',startrow=5,startcol=0)
    sales_gc(region=['Midwest'],week_min=9,week_max=23,sv='No',comp='Yes')\
    .to_excel(writer,sheet_name='Midwest',startrow=5,startcol=0)
    sales_gc(state=['SC','GA','NC','TN','AL'],week_min=9,week_max=23,sv='No',comp='Yes')\
    .to_excel(writer,sheet_name='South No FL',startrow=5,startcol=0)
    sales_gc(state=['FL'],week_min=9,week_max=23,sv='No',comp='Yes')\
    .to_excel(writer,sheet_name='FL',startrow=5,startcol=0)
    sales_gc(fc=['John Martin (FC)'],week_min=9,week_max=23,sv='No',comp='Yes')\
    .to_excel(writer,sheet_name='John Martin',startrow=5,startcol=0)
  
    # Formatting report to Excel
    wb=writer.book
    ws=writer.sheets['Philly']
    ws1=writer.sheets['Baltimore']
    ws2=writer.sheets['DC']
    ws3=writer.sheets['Pittsburgh']
    ws4=writer.sheets['HLLY']
    ws5=writer.sheets['WBS']
    ws6=writer.sheets['Mid-Atl & NE']
    ws7=writer.sheets['Midwest']
    ws8=writer.sheets['South No FL']
    ws9=writer.sheets['FL']
    ws10=writer.sheets['John Martin'] 
    title='Ritas Franchise Company,LLC'
    text1='2024 Philadelphia Growth'
    text2='2024 Baltimore Growth'
    text3='2024 Washington Growth'
    text4='2024 Pittsburgh Growth'
    text5='2024 HLLY Growth'
    text6='2024 Wilke-Barre/Scanton Growth'
    text7='2024 Mid-Atlantic & Northeast Regions Growth'
    text8='2024 Midwest Region Growth'
    text9='2024 South Region(No Florida) Growth'
    text10='2024 Florida Growth'
    text11='2024 John Martin Growth'
    text12='Weeks 9-23'
    text13='Source Code: ritascoolnet_live tmp_raw_pdla'
    header_format=wb.add_format({'bold':True,
                                    'italic':True,
                                    'border':2,
                                    'bg_color':'#2898cc','color':'white'})
    dollar_format=wb.add_format({'num_format':'$#,##0.00'})
    perc_format=wb.add_format({'num_format':'0.0%'}) 
    ws.write(0,1,title,header_format)
    ws.write(1,1,text1,header_format)
    ws.write(2,1,text12,header_format)
    ws.write(3,1,text13,header_format)
    ws.set_column('A:A',15)
    ws.set_column('B:C',30,dollar_format)
    ws.set_column('D:D',30,perc_format)
    
    ws1.write(0,1,title,header_format)
    ws1.write(1,1,text2,header_format)
    ws1.write(2,1,text12,header_format)
    ws1.write(3,1,text13,header_format)
    ws1.set_column('A:A',15)
    ws1.set_column('B:C',30,dollar_format)
    ws1.set_column('D:D',30,perc_format)


    ws2.write(0,1,title,header_format)
    ws2.write(1,1,text3,header_format)
    ws2.write(2,1,text12,header_format)
    ws2.write(3,1,text13,header_format)
    ws2.set_column('A:A',28)
    ws2.set_column('B:C',40,dollar_format)
    ws2.set_column('D:D',30,perc_format)


    ws3.write(0,1,title,header_format)
    ws3.write(1,1,text4,header_format)
    ws3.write(2,1,text12,header_format)
    ws3.write(3,1,text13,header_format)
    ws3.set_column('A:A',28)
    ws3.set_column('B:C',40,dollar_format)
    ws3.set_column('D:D',30,perc_format)


    ws4.write(0,1,title,header_format)
    ws4.write(1,1,text5,header_format)
    ws4.write(2,1,text12,header_format)
    ws4.write(3,1,text13,header_format)
    ws4.set_column('A:A',28)
    ws4.set_column('B:C',40,dollar_format)
    ws4.set_column('D:D',30,perc_format)


    ws5.write(0,1,title,header_format)
    ws5.write(1,1,text6,header_format)
    ws5.write(2,1,text12,header_format)
    ws5.write(3,1,text13,header_format)
    ws5.set_column('A:A',28)
    ws5.set_column('B:C',40,dollar_format)
    ws5.set_column('D:D',30,perc_format)


    ws6.write(0,1,title,header_format)
    ws6.write(1,1,text7,header_format)
    ws6.write(2,1,text12,header_format)
    ws6.write(3,1,text13,header_format)
    ws6.set_column('A:A',28)
    ws6.set_column('B:C',40,dollar_format)
    ws6.set_column('D:D',30,perc_format)


    ws7.write(0,1,title,header_format)
    ws7.write(1,1,text8,header_format)
    ws7.write(2,1,text12,header_format)
    ws7.write(3,1,text13,header_format)
    ws7.set_column('A:A',28)
    ws7.set_column('B:C',40,dollar_format)
    ws7.set_column('D:D',30,perc_format)


    ws8.write(0,1,title,header_format)
    ws8.write(1,1,text9,header_format)
    ws8.write(2,1,text12,header_format)
    ws8.write(3,1,text13,header_format)
    ws8.set_column('A:A',28)
    ws8.set_column('B:C',30,dollar_format)
    ws8.set_column('D:D',30,perc_format)

    ws9.write(0,1,title,header_format)
    ws9.write(1,1,text10,header_format)
    ws9.write(2,1,text12,header_format)
    ws9.write(3,1,text13,header_format)
    ws9.set_column('A:A',28)
    ws9.set_column('B:C',30,dollar_format)
    ws9.set_column('D:D',30,perc_format)


    ws10.write(0,1,title,header_format)
    ws10.write(1,1,text11,header_format)
    ws10.write(2,1,text12,header_format)
    ws10.write(3,1,text13,header_format)
    ws10.set_column('A:A',28)
    ws10.set_column('B:C',30,dollar_format)
    ws10.set_column('D:D',30,perc_format)

    writer.close()