In [1]:
import pandas as pd
import os
import numpy as np
import pyodbc as odbc
from datetime import date,timedelta
os.chdir(r'M:\Natalie Florida 2023 PMIX')

In [2]:
# Names the needed driver, server name, and database
driver_name='SQL Server'
server_name='10.0.1.218'
database='ritascoolnet_live'
#Creates the connection string
connection_string=f"""
DRIVER={{{driver_name}}};
SERVER={server_name};
DATABASE={database};
Trust_Connection=yes"""
#Creates the Connection to SQL Server
connection=odbc.connect(connection_string)
print(connection)
data=pd.read_sql_query('''SELECT *
  FROM [ritas_bi].[dbo].[tmp_raw_plda]
  WHERE YEAR(StartDate)=2023
  ORDER BY Week DESC''',connection)
# data1=pd.read_sql_query('''SELECT *
#   FROM [ritas_bi].[dbo].[tmp_raw_plda]
#   WHERE YEAR(StartDate)=2022
#   ORDER BY Week DESC''',connection)
# data2=pd.read_sql_query('''SELECT *
#   FROM [ritas_bi].[dbo].[tmp_raw_pldb]
#   WHERE YEAR(StartDate)=2021''',connection)
data3=pd.read_sql_query('''Select intstoreid,RitasID as ShopID, FC,CoolNetGroup,LegacyStoreType,State,MSAName,DMA,StoreName as ShopName,StoreStatus,[Special Venue] as SV,SeasonClose from ritascoolnet_live.dbo.vShopDetail''',connection)

<pyodbc.Connection object at 0x0000021F8DF6F6B0>

C:\Users\jharned\AppData\Local\Temp\ipykernel_10952\1308008790.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data=pd.read_sql_query('''SELECT *
C:\Users\jharned\AppData\Local\Temp\ipykernel_10952\1308008790.py:25: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data3=pd.read_sql_query('''Select intstoreid,RitasID as ShopID, FC,CoolNetGroup,LegacyStoreType,State,MSAName,DMA,StoreName as ShopName,StoreStatus,[Special Venue] as SV,SeasonClose from ritascoolnet_live.dbo.vShopDetail''',connection)

In [3]:
# data3=data3[(data3.StoreStatus=='Open')|(data3.StoreStatus=='Ceased Operations')]
# data.shape

In [4]:
# data=data.merge(data3[['ShopID','DMA','MSAName','SeasonClose','SV']],how='left',on='ShopID').drop_duplicates(keep='first')
# data.shape

In [5]:
# fl=data[data.State=='FL'].ShopID.unique()
# fl_sales=data[data.State=='FL'].SalesMny.sum()
# fl_qty=data[data.State=='FL'].SalesQty.sum()
# for i in list(enumerate(fl)):
#         fl_sales=data[(data.ShopID==i[1])&(data.Week.between(9,27))].SalesMny.sum()
#         fl_qty=data[(data.ShopID==i[1])&(data.Week.between(9,27))].SalesQty.sum()
#         s_cat23=data[(data.ShopID==i[1])&(data.Week.between(9,27))].pivot_table(index='ProductTypeName',columns='Week',
#                                                values='SalesMny',aggfunc='sum',fill_value=0).reset_index()
#         q_cat23=data[(data.ShopID==i[1])&(data.Week.between(9,27))].pivot_table(index='ProductTypeName',columns='Week',
#                                                values='SalesQty',aggfunc='sum',fill_value=0).reset_index()
#         s_pcat23=data[(data.ShopID==i[1])&(data.Week.between(9,27))].pivot_table(index='ProductTypeName',columns='Week',
#                                                values='SalesMny',aggfunc='sum',fill_value=0).apply(lambda x:x/x.sum()).reset_index()
#         q_pcat23=data[(data.ShopID==i[1])&(data.Week.between(9,27))].pivot_table(index='ProductTypeName',columns='Week',
#                                                values='SalesQty',aggfunc='sum',fill_value=0).apply(lambda x:x/x.sum()).reset_index()
#         s_pcat23=s_pcat23.rename(columns={'SalesMny':'Sales%'})
#         q_pcat23=q_pcat23.rename(columns={'SalesQty':'Qty%'})    
#         s_item23=data[(data.ShopID==i[1])&(data.Week.between(9,27))].pivot_table(index='ProductSizeName',columns='Week',
#                                                values='SalesMny',aggfunc='sum',fill_value=0).reset_index()
#         q_item23=data[(data.ShopID==i[1])&(data.Week.between(9,27))].pivot_table(index='ProductSizeName',columns='Week',
#                                                values='SalesQty',aggfunc='sum',fill_value=0).reset_index()
#         s_pitem23=data[(data.ShopID==i[1])&(data.Week.between(9,27))].pivot_table(index='ProductSizeName',columns='Week',
#                                                values='SalesMny',aggfunc='sum',fill_value=0).apply(lambda x:x/x.sum()).reset_index()
#         q_pitem23=data[(data.ShopID==i[1])&(data.Week.between(9,27))].pivot_table(index='ProductSizeName',columns='Week',
#                                                values='SalesQty',aggfunc='sum',fill_value=0).apply(lambda x:x/x.sum()).reset_index()
#         s_pitem23=s_pitem23.rename(columns={'SalesMny':'Sales%'})
#         q_pitem23=q_pitem23.rename(columns={'SalesQty':'Qty%'})
# #         print(q_pitem23.info())
#         writer=pd.ExcelWriter('FL Shop '+str(i[1])+' PMIX Week 9-27.xlsx',engine='xlsxwriter')
#         s_cat23.sort_values(by=[27],ascending=False).to_excel(writer, sheet_name='Category Sales Shop '+str(i[1]),float_format="%0.3f")
#         s_pcat23.sort_values(by=[27],ascending=False).to_excel(writer, sheet_name='Category Sales% Shop '+str(i[1]),float_format="%0.3f")
#         q_cat23.sort_values(by=[27],ascending=False).to_excel(writer, sheet_name='Category Qty Shop '+str(i[1]),float_format="%0.3f")
#         q_pcat23.sort_values(by=[27],ascending=False).to_excel(writer, sheet_name='Category Qty% Shop '+str(i[1]),float_format="%0.3f")
#         s_item23.sort_values(by=[27],ascending=False).to_excel(writer, sheet_name='Item Sales Shop ' +str(i[1]),float_format="%0.3f")
#         s_pitem23.sort_values(by=[27],ascending=False).to_excel(writer, sheet_name='Item Sales% Shop ' +str(i[1]),float_format="%0.3f")
#         q_item23.sort_values(by=[27],ascending=False).to_excel(writer, sheet_name='Item Qty Shop ' +str(i[1]),float_format="%0.3f")
#         q_pitem23.sort_values(by=[27],ascending=False).to_excel(writer, sheet_name='Item Qty% Shop ' +str(i[1]),float_format="%0.3f")
#         workbook=writer.book
#         worksheet=writer.sheets['Category Sales Shop '+str(i[1])]
#         worksheet_1=writer.sheets['Category Sales% Shop '+str(i[1])]
#         worksheet_2=writer.sheets['Category Qty Shop '+str(i[1])]
#         worksheet_3=writer.sheets['Category Qty% Shop '+str(i[1])]
#         worksheet_4=writer.sheets['Item Sales Shop '+str(i[1])]
#         worksheet_5=writer.sheets['Item Sales% Shop '+str(i[1])]
#         worksheet_6=writer.sheets['Item Qty Shop '+str(i[1])]
#         worksheet_7=writer.sheets['Item Qty% Shop '+str(i[1])]
        
        
#         format_1=workbook.add_format({'num_format':'0.00%'})
#         format_2=workbook.add_format({'num_format':'$#,##0.00'})
#         format_3=workbook.add_format({'num_format':'#,##0'})
#         worksheet.set_column('B:B',30)
#         worksheet.set_column('C:Z',12,format_2)
#         worksheet_1.set_column('B:B',30)
#         worksheet_1.set_column('C:Z',12,format_1)
#         worksheet_2.set_column('B:B',30)
#         worksheet_2.set_column('C:Z',12,format_3)
#         worksheet_3.set_column('B:B',30)
#         worksheet_3.set_column('C:Z',12,format_1)
#         worksheet_4.set_column('B:B',30)
#         worksheet_4.set_column('C:Z',12,format_2)
#         worksheet_5.set_column('B:B',30)
#         worksheet_5.set_column('C:Z',12,format_1)
#         worksheet_6.set_column('B:B',30)
#         worksheet_6.set_column('C:Z',12,format_3)
#         worksheet_7.set_column('B:B',30)
#         worksheet_7.set_column('C:Z',12,format_1)
#         writer.close()

In [6]:
# small=['Small Ice','Small Gelati','Small Gelati Blender','Small Ice Blender']
# weeks=[18,19,20,21]
# data[(data.ProductSizeName.isin(small))&(data.Week.isin(weeks))].pivot_table(index=['ShopID','ShopName'],
#                                                                               columns=['ProductSizeName','Week'],
#                                                                              values=['SalesMny','SalesQty'],
#                                                                              aggfunc='sum',
#                                                                              fill_value=0).to_excel('Test.xlsx')

In [7]:
# small=['Small Frozen Lemonade']
# weeks=[32,33,34,35,36]
# data[(data.ProductSizeName.isin(small))&(data.Week.isin(weeks))].pivot_table(index=['ShopID','ShopName'],
#                                                                               columns=['ProductSizeName','Week'],
#                                                                              values=['SalesMny','SalesQty'],
#                                                                              aggfunc='sum',
#                                                                              fill_value=0).to_excel('Lemonade Sales Qty.xlsx')

In [3]:
df=pd.read_sql_query('''SELECT *
  FROM [ritas_bi].[dbo].[tmp_raw_plda]
  WHERE YEAR(StartDate)>=2023
  ORDER BY Week DESC''',connection)

C:\Users\jharned\AppData\Local\Temp\ipykernel_10952\3427698466.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query('''SELECT *

In [4]:
df=df.merge(data3[['ShopID','DMA','MSAName','SeasonClose','SV']],how='left',on='ShopID').drop_duplicates(keep='first')

In [6]:
os.chdir(r'M:\Natalie Florida 2023 PMIX\2024 PMIX')
fl=df[df.State=='FL'].ShopID.unique()
df['Year']=df.StartDate.dt.year
week_max=df[df.Year==df.Year.max()].Week.max()
for i in list(enumerate(fl)):
    fl_qty=df[(df.ShopID==i[1])&(df.Week.between(9,week_max))].SalesQty.sum()
    qty_cat=df[(df.ShopID==i[1])&(df.Week.between(9,week_max))].pivot_table(index='ProductTypeName',columns=['Week','Year'],
                                               values='SalesQty',aggfunc='sum',fill_value=0).reset_index()
    qty_item=df[(df.ShopID==i[1])&(df.Week.between(9,week_max))].pivot_table(index='ProductSizeName',columns=['Week','Year'],
                                               values='SalesQty',aggfunc='sum',fill_value=0).reset_index()
    pqty_cat=df[(df.ShopID==i[1])&(df.Week.between(9,week_max))].pivot_table(index='ProductTypeName',columns=['Week','Year'],
                                               values='SalesQty',aggfunc='sum',fill_value=0).apply(lambda x:x/x.sum()).reset_index()
    pqty_item=df[(df.ShopID==i[1])&(df.Week.between(9,week_max))].pivot_table(index='ProductSizeName',columns=['Week','Year'],
                                               values='SalesQty',aggfunc='sum',fill_value=0).apply(lambda x:x/x.sum()).reset_index()
    writer=pd.ExcelWriter('FL Shop '+str(i[1])+' PMIX 24 v 23.xlsx',engine='xlsxwriter')
    qty_cat.sort_values(by=qty_cat.columns[-1],ascending=False).to_excel(writer, sheet_name='Qty Sold Category Shop '+ str(i[1]))
    pqty_cat.sort_values(by=pqty_cat.columns[-1],ascending=False).to_excel(writer, sheet_name='Qty% Sold Category Shop '+ str(i[1]))
    qty_item.sort_values(by=qty_item.columns[-1],ascending=False).to_excel(writer, sheet_name='Qty Sold Item Shop '+ str(i[1]))
    pqty_item.sort_values(by=pqty_item.columns[-1],ascending=False).to_excel(writer, sheet_name='Qty% Sold Item Shop '+ str(i[1]))
    workbook=writer.book
    worksheet=writer.sheets['Qty Sold Category Shop '+str(i[1])]
    worksheet_1=writer.sheets['Qty% Sold Category Shop '+str(i[1])]
    worksheet_2=writer.sheets['Qty Sold Item Shop '+str(i[1])]
    worksheet_3=writer.sheets['Qty% Sold Item Shop '+str(i[1])]
    format_1=workbook.add_format({'num_format':'0.00%'})
    format_2=workbook.add_format({'num_format':'#,##0'})
    worksheet.set_column('B:B',30)
    worksheet.set_column('C:CC',12,format_2)
    worksheet_1.set_column('B:B',30)
    worksheet_1.set_column('C:CC',12,format_1)
    worksheet_2.set_column('B:B',30)
    worksheet_2.set_column('C:CC',12,format_2)
    worksheet_3.set_column('B:B',30)
    worksheet_3.set_column('C:CC',12,format_1)
    writer.close()

In [ ]:
# df.columns[-1]

In [8]:
    fl=df[df.State=='FL']
    df['Year']=df.StartDate.dt.year
    week_max=df[df.Year==df.Year.max()].Week.max()-4

    fl_qty=fl[(fl.Week.between(9,week_max))].SalesQty.sum()
    qty_cat=fl[(fl.Week.between(9,week_max))].pivot_table(index='ProductTypeName',columns=['Week','Year'],
                                               values='SalesQty',aggfunc='sum',fill_value=0).reset_index()
    qty_item=fl[(fl.Week.between(9,week_max))].pivot_table(index='ProductSizeName',columns=['Week','Year'],
                                               values='SalesQty',aggfunc='sum',fill_value=0).reset_index()
    pqty_cat=fl[(fl.Week.between(9,week_max))].pivot_table(index='ProductTypeName',columns=['Week','Year'],
                                               values='SalesQty',aggfunc='sum',fill_value=0).apply(lambda x:x/x.sum()).reset_index()
    pqty_item=fl[(fl.Week.between(9,week_max))].pivot_table(index='ProductSizeName',columns=['Week','Year'],
                                               values='SalesQty',aggfunc='sum',fill_value=0).apply(lambda x:x/x.sum()).reset_index()
    writer=pd.ExcelWriter('FL Shops Rolled Up PMIX 24 v 23 v2.xlsx',engine='xlsxwriter')
    qty_cat.sort_values(by=qty_cat.columns[-1],ascending=False).to_excel(writer, sheet_name='Qty Sold Category Shop ')
    pqty_cat.sort_values(by=pqty_cat.columns[-1],ascending=False).to_excel(writer, sheet_name='Qty% Sold Category Shop ')
    qty_item.sort_values(by=qty_item.columns[-1],ascending=False).to_excel(writer, sheet_name='Qty Sold Item Shop ')
    pqty_item.sort_values(by=pqty_item.columns[-1],ascending=False).to_excel(writer, sheet_name='Qty% Sold Item Shop ')
    workbook=writer.book
    worksheet=writer.sheets['Qty Sold Category Shop ']
    worksheet_1=writer.sheets['Qty% Sold Category Shop ']
    worksheet_2=writer.sheets['Qty Sold Item Shop ']
    worksheet_3=writer.sheets['Qty% Sold Item Shop ']
    format_1=workbook.add_format({'num_format':'0.0%'})
    format_2=workbook.add_format({'num_format':'#,##0'})
    worksheet.set_column('B:B',30)
    worksheet.set_column('C:CC',12,format_2)
    worksheet_1.set_column('B:B',30)
    worksheet_1.set_column('C:CC',12,format_1)
    worksheet_2.set_column('B:B',30)
    worksheet_2.set_column('C:CC',12,format_2)
    worksheet_3.set_column('B:B',30)
    worksheet_3.set_column('C:CC',12,format_1)
    writer.close()

In [9]:
week_max

27

In [28]:
    week_max=df[df.Year==df.Year.max()].Week.max()-2
    df['Year']=df.StartDate.dt.year
    fl_qty=df[(df.Week.between(9,week_max))].SalesQty.sum()
    fl_df=df[df.State=='FL']
    qty_cat=fl_df[(fl_df.Week.between(9,week_max))].pivot_table(index='ProductTypeName',columns=['Year'],
                                               values='SalesQty',aggfunc='sum',fill_value=0).reset_index()
    qty_item=fl_df[(fl_df.Week.between(9,week_max))].pivot_table(index='ProductSizeName',columns=['Year'],
                                               values='SalesQty',aggfunc='sum',fill_value=0).reset_index()
    pqty_cat=fl_df[(fl_df.Week.between(9,week_max))].pivot_table(index='ProductTypeName',columns=['Year'],
                                               values='SalesQty',aggfunc='sum',fill_value=0).apply(lambda x:x/x.sum()).reset_index()
    pqty_item=fl_df[(fl_df.Week.between(9,week_max))].pivot_table(index='ProductSizeName',columns=['Year'],
                                               values='SalesQty',aggfunc='sum',fill_value=0).apply(lambda x:x/x.sum()).reset_index()
    writer=pd.ExcelWriter('FL Shop PMIX 24 v 23.xlsx',engine='xlsxwriter')
    qty_cat.sort_values(by=qty_cat.columns[-1],ascending=False).to_excel(writer, sheet_name='Qty Sold Category Shop ')
    pqty_cat.sort_values(by=pqty_cat.columns[-1],ascending=False).to_excel(writer, sheet_name='Qty% Sold Category Shop ')
    qty_item.sort_values(by=qty_item.columns[-1],ascending=False).to_excel(writer, sheet_name='Qty Sold Item Shop ')
    pqty_item.sort_values(by=pqty_item.columns[-1],ascending=False).to_excel(writer, sheet_name='Qty% Sold Item Shop ')
    workbook=writer.book
    worksheet=writer.sheets['Qty Sold Category Shop ']
    worksheet_1=writer.sheets['Qty% Sold Category Shop ']
    worksheet_2=writer.sheets['Qty Sold Item Shop ']
    worksheet_3=writer.sheets['Qty% Sold Item Shop ']
    format_1=workbook.add_format({'num_format':'0.00%'})
    format_2=workbook.add_format({'num_format':'#,##0'})
    worksheet.set_column('B:B',30)
    worksheet.set_column('C:CC',12,format_2)
    worksheet_1.set_column('B:B',30)
    worksheet_1.set_column('C:CC',12,format_1)
    worksheet_2.set_column('B:B',30)
    worksheet_2.set_column('C:CC',12,format_2)
    worksheet_3.set_column('B:B',30)
    worksheet_3.set_column('C:CC',12,format_1)
    writer.close()

In [29]:
    df['Year']=df.StartDate.dt.year
    week_max=df[df.Year==df.Year.max()].Week.max()
    fl_qty=df[(df.Week.between(9,week_max))].SalesQty.sum()
    fl_df=df[df.State=='FL']
    qty_cat=fl_df[(fl_df.Week.between(9,week_max))].pivot_table(index='ProductTypeName',columns=['Year'],
                                               values='SalesQty',aggfunc='sum',fill_value=0).reset_index()
    qty_item=fl_df[(fl_df.Week.between(9,week_max))].pivot_table(index='ProductSizeName',columns=['Year'],
                                               values='SalesQty',aggfunc='sum',fill_value=0).reset_index()
    pqty_cat=fl_df[(fl_df.Week.between(9,week_max))].pivot_table(index='ProductTypeName',columns=['Year'],
                                               values='SalesQty',aggfunc='sum',fill_value=0).apply(lambda x:x/x.sum()).reset_index()
    pqty_item=fl_df[(fl_df.Week.between(9,week_max))].pivot_table(index='ProductSizeName',columns=['Year'],
                                               values='SalesQty',aggfunc='sum',fill_value=0).apply(lambda x:x/x.sum()).reset_index()

In [33]:
qty_cat.sort_values(by=qty_cat.columns[-1],ascending=False)

Year                 ProductTypeName    2023    2024
22                       Italian Ice  373159  389375
9                            Custard  302280  372344
16                            Gelati  265769  310635
1                Additional Toppings   62239   66215
5                           Concrete   59009   64586
23                        Milkshakes   44606   47912
21                       Ice Blender   15596   39748
30                         Sprinkles   25956   35140
0                 3rd Party Delivery      57   27107
17                    Gelati Blender   25833   24767
19              Hand Scooped Custard   23849   20410
2                          Beverages   10163   13422
12                     Frozen Coffee   12698   12721
3                           Blendini   14920   12210
6                  Cookie Sandwiches    3989   10282
26           Non-Coded Revenue Sales    9564    8819
13                  Frozen Lemonades       2    7697
27           Novelty Custard (Pints)    3112    4015
25                           Nathans    1436    1415
29                            Snacks     862     704
28                   Online Ordering       0     570
4                Catering (Bulk Ice)    1021     551
11                Fresh Baked Treats     277     250
14    Full Service Catering (Open $)     128     189
10                          Discount       0      68
8          Cool Stuff Consumer Goods      11      53
15                  Fundraiser Cards       1       5
24                        MobileCart       3       3
18                        Good to Go       1       1
20                        Hot Drinks       0       0
7                            Cookies       0       0
31                            Yogurt       0       0